//
//  LocalizationService+EN.swift
//  ChefOS
//

extension LocalizationService {
    static let en: [String: String] = [
        // Tabs
        "tab.chat": "Chat",
        "tab.recipes": "Recipes",
        "tab.plan": "Plan",
        "tab.profile": "Profile",

        // Profile sections
        "profile.title": "Profile",
        "profile.personalInfo": "Personal Info",
        "profile.goals": "Goals",
        "profile.preferences": "Preferences",
        "profile.restrictions": "Restrictions",
        "profile.lifestyle": "Lifestyle",
        "profile.region": "Region",

        // Profile fields
        "profile.age": "Age",
        "profile.weight": "Weight (kg)",
        "profile.goal": "Goal",
        "profile.targetWeight": "Target weight (kg)",
        "profile.caloriesDay": "Calories / day",
        "profile.protein": "Protein (g)",
        "profile.diet": "Diet",
        "profile.cuisine": "Cuisine",
        "profile.likes": "Likes",
        "profile.dislikes": "Dislikes",
        "profile.allergies": "Allergies",
        "profile.conditions": "Conditions",
        "profile.cookingLevel": "Cooking level",
        "profile.cookingTime": "Cooking time",
        "profile.mealsDay": "Meals / day",
        "profile.country": "Country",
        "profile.currency": "Currency",
        "profile.language": "Language",
        "profile.security": "Security",
        "profile.signOut": "Sign out",
        "profile.autoSaved": "Auto-saved",
        "profile.save": "Save Changes",
        "profile.saved": "Saved ✓",

        // AI Summary
        "profile.aiTitle": "ChefOS understands you",
        "profile.aiSubtitle": "Based on your profile",

        // Tags
        "tags.addLikes": "Add likes…",
        "tags.addDislikes": "Add dislikes…",
        "tags.addAllergies": "Add allergies…",
        "tags.addConditions": "Add conditions…",

        // Fitness goals
        "goal.loseFat": "Lose fat",
        "goal.gainMuscle": "Gain muscle",
        "goal.maintainWeight": "Maintain weight",
        "goal.eatHealthier": "Eat healthier",
        "goal.medicalDiet": "Medical diet",

        // Diet types
        "diet.noRestrictions": "No restrictions",
        "diet.vegetarian": "Vegetarian",
        "diet.vegan": "Vegan",
        "diet.keto": "Keto",
        "diet.paleo": "Paleo",
        "diet.glutenFree": "Gluten-free",
        "diet.dairyFree": "Dairy-free",

        // Cuisine
        "cuisine.any": "Any",
        "cuisine.asian": "Asian",
        "cuisine.mediterranean": "Mediterranean",
        "cuisine.american": "American",
        "cuisine.mexican": "Mexican",
        "cuisine.italian": "Italian",
        "cuisine.middleEastern": "Middle Eastern",

        // Cooking level
        "cooking.beginner": "Beginner",
        "cooking.homeCook": "Home cook",
        "cooking.advanced": "Advanced",
        "cooking.chef": "Chef",

        // Cooking time
        "time.quick": "≤ 15 min",
        "time.medium": "≤ 30 min",
        "time.long": "≤ 60 min",
        "time.any": "Any",

        // AI Summary labels
        "ai.goal": "Goal",
        "ai.calories": "Calories",
        "ai.kcal": "kcal",
        "ai.protein": "Protein",
        "ai.g": "g",
        "ai.diet": "Diet",
        "ai.avoid": "Avoid",
        "ai.time": "Time",
        "ai.level": "Level",

        // Chat
        "chat.title": "Chat",
        "chat.placeholder": "Start with anything…",
        "chat.send": "Send",
        "chat.actionsLeft": "AI actions left today:",
        "chat.purchased": "purchased",
        "chat.thinking": "ChefOS is thinking",
        "chat.welcome": "Hi! I'm your ChefOS assistant.\nWhat are we cooking today?",
        "chat.welcomePersonal": "Hi, {name}! 👋 I'm your personal ChefOS assistant.\nLet's make today delicious!",
        "chat.error": "Something went wrong. Please try again.",
        "chat.error.network": "No internet connection. Check your network and try again.",
        "chat.error.server": "The server is temporarily unavailable. Please try again in a moment.",
        "chat.error.rate_limited": "Too many requests. Please wait a few seconds.",
        "chat.error.unauthorized": "Session expired. Please sign in again.",
        "chat.ai": "AI",
        "chat.photo": "Photo",
        "chat.voice": "Voice",
        "chat.ingredients": "ingredients",
        "chat.motivation.loseWeight": "🔥 Your goal is weight loss — I'll suggest light, low-calorie dishes!",
        "chat.motivation.gainMuscle": "💪 Your goal is muscle gain — I'll focus on high-protein meals!",
        "chat.motivation.gainWeight": "🍖 Your goal is weight gain — I'll suggest calorie-dense, nutritious meals!",
        "chat.motivation.eatHealthier": "🥗 You want to eat healthier — I'll pick balanced, wholesome recipes!",
        "chat.motivation.balanced": "🎯 Let's keep your nutrition balanced and delicious!",
        "chat.motivation.diet": "📋 I remember your diet: {diet}. All suggestions will respect it.",
        "chat.motivation.targets": "🎯 Daily targets: {kcal} kcal, {protein}g protein. I'll help you stay on track!",
        "chat.motivation.allergies": "⚠️ I'll avoid: {list}. Your safety comes first!",

        // Chat cards (structured greeting flow)
        "chat.goal.loseWeight":    "Lose Weight",
        "chat.goal.gainMuscle":    "Build Muscle",
        "chat.goal.gainWeight":    "Gain Weight",
        "chat.goal.eatHealthier":  "Eat Healthier",
        "chat.goal.balanced":      "Balanced Nutrition",

        "chat.focus.loseWeight":   "Focus: light, low-calorie dishes",
        "chat.focus.gainMuscle":   "Focus: high-protein meals",
        "chat.focus.gainWeight":   "Focus: calorie-dense, nutritious meals",
        "chat.focus.eatHealthier": "Focus: balanced, wholesome recipes",
        "chat.focus.balanced":     "Focus: balanced and delicious",

        // Chat action buttons
        "chat.action.addToPlan":      "Add to Plan",
        "chat.action.cook":           "Start Cooking",
        "chat.action.swap":           "Swap",
        "chat.action.addToCart":      "Add to Cart",
        "chat.action.addToInventory": "Add to Stock",
        "chat.action.moreInfo":       "Details",
        "chat.action.showRecipes":    "Show Recipes",
        "chat.action.steps":          "steps",
        "chat.action.added.title":    "Added to today's plan",
        "chat.action.cooking.title":  "Ready to cook",
        "chat.action.shopping.title": "Added to shopping list",
        "chat.action.inventory.title": "Added to stock",
        "chat.action.swap.query":     "Suggest an alternative to {ingredient} in {recipe}",
        "chat.action.showRecipes.query": "Show me recipes with {product}",

        "profile.years": "y.o.",

        // Onboarding
        "onboarding.welcome": "Welcome to ChefOS",
        "onboarding.signIn": "Sign In",
        "onboarding.signUp": "Sign Up",
        "onboarding.email": "Email",
        "onboarding.password": "Password",
        "onboarding.name": "Your name",
        "onboarding.restaurantName": "Restaurant name",
        "onboarding.passwordHint": "Min 8 characters, at least one letter and one number",
        "onboarding.noAccount": "Don't have an account?",
        "onboarding.haveAccount": "Already have an account?",
        "onboarding.continue": "Continue",
        "onboarding.done": "Done",
        "onboarding.subtitle": "Your AI cooking assistant",
        "onboarding.detecting": "Detecting your region…",
        "onboarding.currency": "Currency:",
        "onboarding.changeCountry": "Change country",
        "onboarding.createAccount": "Create Account",
        "onboarding.welcomeBack": "Welcome back to ChefOS",
        "onboarding.startJourney": "Start your cooking journey",
        "onboarding.kitchenName": "Your kitchen name",
        "onboarding.enableBiometric": "Enable",
        "onboarding.secureAccess": "Secure access to your data with",
        "onboarding.maybeLater": "Maybe later",
        "onboarding.tapToUnlock": "Tap to unlock",
        "onboarding.searchCountries": "Search countries",
        "onboarding.country": "Country",

        // Plan
        "plan.title": "Meal Plan",
        "plan.day": "Day",
        "plan.week": "Week",
        "plan.generationsLeft": "Plan generations left",
        "plan.resetsIn": "Resets in",
        "plan.saves": "This plan saves you",
        "plan.today": "today",
        "plan.overBudget": "You're over budget — Optimize now",
        "plan.smartPlan": "Smart Plan",
        "plan.generating": "Generating…",
        "plan.aiThinking": "AI is thinking",
        "plan.generateAll": "Generate all meals",
        "plan.optimize": "Optimize",
        "plan.planReady": "Plan ready",
        "plan.optimizedGoals": "— optimized for your goals",
        "plan.addedTo": "Added to",
        "plan.weekOverview": "Week Overview",
        "plan.meals": "meals",
        "plan.days": "days",
        "plan.noMeals": "No meals planned",
        "plan.tapGenerate": "Tap to generate",
        "plan.mainMeal": "Main meal",
        "plan.replace": "Replace",
        "plan.addMeal": "Add meal",
        "plan.tapToExpand": "Tap to expand",
        "plan.needToBuy": "Need to Buy",
        "plan.shoppingList": "Shopping List for Today",
        "plan.tapToCollapse": "Tap to collapse",
        "plan.ingredients": "Ingredients",
        "plan.steps": "Steps",
        "plan.stepsCount": "steps",
        "plan.breakfast": "Breakfast",
        "plan.lunch": "Lunch",
        "plan.dinner": "Dinner",
        "plan.kcal": "kcal",
        "plan.gProtein": "g protein",
        "plan.gP": "g P",
        "plan.gF": "g F",
        "plan.gC": "g C",
        "plan.noMealsYet": "No meals yet — tap Generate to start",
        "plan.withinBudget": "Within budget",
        "plan.overBudgetBy": "Over budget by %@ %@",
        "plan.hint.loadRecipes": "Loading recipes from your stock…",
        "plan.hint.generateDay": "Tap Generate to create today's plan",
        "plan.hint.balanced": "Great balance! Nutrition looks good 👌",
        "plan.hint.lowProtein": "Add %@ g more protein-rich dishes",
        "plan.hint.overCalories": "Over by %@ kcal — try lighter options",
        "plan.hint.overBudget": "Over budget by %@ %@ — swap cheaper",
        "plan.hint.emptySlots": "%@ meal slots still empty",
        "plan.hint.onTrack": "You're on track — keep it up! 🎯",

        // Recipes
        "recipes.title": "Recipes",
        "recipes.search": "Search recipes…",
        "recipes.searchStock": "Search stock…",
        "recipes.stock": "Stock",
        "recipes.cook": "Cook",
        "recipes.total": "Total",
        "recipes.items": "Items",
        "recipes.expiring": "Expiring",
        "recipes.noItems": "No items found",
        "recipes.scanReceipt": "Scan a receipt in Chat to add items",
        "recipes.strategy": "Strategy for today",
        "recipes.basedOnStock": "Based on your stock",
        "recipes.canCookNow": "Can cook now",
        "recipes.canCook": "can cook now",
        "recipes.missingIngredients": "Missing ingredients",
        "recipes.missing": "missing",
        "recipes.noRecipes": "No recipes found",
        "recipes.cookBtn": "Cook",
        "recipes.cookNow": "Cook now",
        "recipes.addToPlan": "Add to plan",
        "recipes.added": "Added",
        "recipes.addShopping": "Add to shopping list",
        "recipes.addMissingShopping": "Add missing to shopping list",
        "recipes.showIngredients": "Show ingredients",
        "recipes.hideIngredients": "Hide ingredients",
        "recipes.ingredients": "Ingredients",
        "recipes.steps": "Steps",
        "recipes.portion": "/ portion",
        "recipes.totalCost": "total",
        "recipes.ofBudget": "of budget",
        "recipes.allInStock": "All ingredients in stock",
        "recipes.missingCount": "Missing %d ingredient(s)",
        "recipes.cooked": "Cooked!",
        "recipes.stockUpdated": "Stock updated",
        "recipes.addProduct": "Add product",
        "recipes.catalogSearch": "Search catalog…",
        "recipes.allCategories": "All",
        "recipes.quantity": "Quantity",
        "recipes.price": "Price",
        "recipes.expiryDays": "Expires in (days)",
        "recipes.purchaseDate": "Purchase date",
        "recipes.expiryDate": "Best before",
        "recipes.shelfLife": "Shelf life",
        "recipes.addToStock": "Add to stock",
        "recipes.adding": "Adding…",
        "recipes.unit": "Unit",
        "recipes.calories": "kcal/100g",
        "recipes.noResults": "No ingredients found",
        "recipes.trySearch": "Try a different search or category",
        "recipes.yourSettings": "Your settings",
        "recipes.days": "days",
        "recipes.expirestoday": "expires today",
        "recipes.daysLeft": "d left",
        "recipes.categoryLabel": "Category",
        "recipes.unitLabel": "Unit",
        "recipes.pricePerUnit": "Price per unit",
        "recipes.severity": "Status",
        "recipes.delete": "Remove from stock",
        "recipes.filterAll": "All",
        "recipes.filterExpiring": "Expiring",
        "recipes.filterLow": "Low",
        "recipes.atRisk": "At risk",
        "recipes.smartInsight": "Smart Insight",
        "recipes.insightWaste": "Potential losses:",
        "recipes.insightAllGood": "All products are fresh!",
        "recipes.insightExpired": "expired!",
        "recipes.insightTomorrow": "expires tomorrow!",
        "recipes.insightDaysLeft": "days left — use first",
        "recipes.whatToCook": "What to cook from this?",
        "recipes.insightEmpty": "Add products to get smart insights",
        "recipes.insightUrgent": "%d products need attention — use them today",
        "recipes.insightGood": "You have products for ~%d days — all fresh!",
        "recipes.useToday": "Use today!",
        "recipes.daysUseFirst": "days — use first",
        "recipes.replace": "Replace",
        "recipes.empty": "Empty",
        "recipes.plan": "Plan",
        "recipes.servings": "srv",
        "recipes.stepsCount": "steps",

        // Cook
        "cook.title": "What to Cook",
        "cook.favorites": "Favorites",
        "cook.noFavorites": "No favorite recipes yet",
        "cook.noFavoritesHint": "Generate recipes in Stock tab and tap ❤️ to save your favorites here",
        "cook.removeFromFavorites": "Remove from favorites",
        "cook.stepsNotAvailable": "Full steps available when you open the recipe",
        "cook.perServing": "Per serving",
        "cook.ingredientsCount": "Ingredients",
        "cook.steps": "Steps",
        "cook.analyzing": "Analyzing your inventory…",
        "cook.retry": "Try Again",
        "cook.error": "Something went wrong",
        "cook.empty": "Add more products to get suggestions",
        "cook.emptyDescription": "Add products to your inventory and we'll suggest what to cook",
        "cook.missing": "missing",
        "cook.openRecipe": "Open Recipe",
        "cook.canCookNow": "Ready to Cook",
        "cook.almostReady": "Almost Ready",
        "cook.strategic": "Smart Picks",
        "cook.noProducts": "No products yet",
        "cook.noProductsHint": "Add products to your inventory and I'll suggest what to cook",
        "cook.addProducts": "Add Products",
        "cook.addHint": "Add at least 2–3 products and I'll suggest what to cook",
        "cook.youHave": "You have",
        "cook.notEnough": "Not enough products for a recipe",
        "cook.notEnoughHint": "Add a few more ingredients to unlock recipe suggestions",
        "cook.recommend": "Recommended to add",
        "cook.addProtein": "Protein (chicken / eggs / fish)",
        "cook.addBase": "Base (rice / pasta / potatoes)",
        "cook.addVegetable": "Vegetables (onion / tomato / carrot)",
        "cook.unlockHint": "+1 product → unlock recipe suggestions",
        "cook.yourIngredients": "Your ingredients",
        "cook.noRecipesFound": "No recipes found for your products",
        "cook.tryAddMore": "Try adding more diverse ingredients",
        "cook.refreshSuggestions": "Refresh suggestions",
        "cook.generateRecipes": "✨ What to cook from this?",
        "cook.analysis": "Analysis",
        "cook.noProtein": "No protein — can't build a full meal",
        "cook.hasProtein": "Protein — ✓",
        "cook.noBase": "No base (carbs) — nothing to serve with",
        "cook.hasBase": "Base — ✓",
        "cook.noVegetable": "No vegetables — missing freshness",
        "cook.hasVegetable": "Vegetables — ✓",
        "cook.cantCookFull": "Can't assemble a complete dish yet",
        "cook.almostThere": "Almost there — one more type and you're set!",
        "cook.chicken": "Chicken",
        "cook.eggs": "Eggs",
        "cook.fish": "Fish",
        "cook.rice": "Rice",
        "cook.pasta": "Pasta",
        "cook.potato": "Potato",
        "cook.onion": "Onion",
        "cook.tomato": "Tomato",
        "cook.carrot": "Carrot",
        "cook.recipesLocked": "Recipes locked",
        "cook.addMoreToUnlock": "Add %d more product(s) to unlock",
        "cook.tryAnyway": "✨ Try to find a recipe anyway",
        "cook.browseCatalog": "Browse full catalog",
        "cook.actionTitle": "Add product",
        "cook.personalizedForYou": "Personalized for you",
        "cook.yourGoal": "Your goal",
        "cook.yourDiet": "Diet",
        "cook.excluded": "Excluded",
        "cook.dislikesExcluded": "Not for you",
        "cook.goal.loseWeight": "Weight loss",
        "cook.goal.gainMuscle": "Muscle gain",
        "cook.goal.gainWeight": "Weight gain",
        "cook.goal.eatHealthier": "Eat healthier",
        "cook.goal.balanced": "Balanced",
        "cook.diet.vegan": "Vegan",
        "cook.diet.vegetarian": "Vegetarian",
        "cook.diet.pescatarian": "Pescatarian",
        "cook.diet.keto": "Keto",
        "cook.badge.highProtein": "High Protein",
        "cook.badge.lowCal": "Low Cal",
        "cook.badge.allergenFree": "Allergen-free",
        "cook.badge.quick": "Quick",
        "cook.badge.budget": "Budget",
        "cook.reason.fitsGoal": "Fits your goal",
        "cook.reason.usesInventory": "Uses your ingredients",
        "cook.actionMessage": "What to do with %@?",
        "cook.toShoppingList": "🛒 Add to shopping list",
        "cook.toInventory": "📦 Add to inventory",
        "cook.addedFromCook": "Added from recipe suggestions",
        "cook.shoppingList": "Shopping List",
        "cook.ingredients": "Ingredients",
        "cook.daysLeft": "Days left",
        "cook.wasteRisk": "Waste risk",
        "cook.unlockMore": "Unlock more recipes",
        "cook.tapForRecipe": "Tap for full recipe",
        "cook.stepsCount": "steps",
        "cook.min": "min",
        "cook.whyThisDish": "Why this dish",
        "cook.nutrition": "Nutrition",
        "cook.perServingCount": "Per serving",
        "cook.kcal": "kcal",
        "cook.protein": "Protein",
        "cook.fat": "Fat",
        "cook.carbs": "Carbs",
        "cook.flavorProfile": "Flavor profile",
        "cook.balance": "Balance",
        "cook.dominant": "Dominant:",
        "cook.canImprove": "Can improve:",
        "cook.adapted": "Optimized",
        "cook.optimizedFor": "Optimized for:",
        "cook.ingredientsList": "Ingredients",
        "cook.needToBuy": "Need to buy",
        "cook.cookingSteps": "Cooking steps",
        "cook.warnings": "Warnings",
        "cook.tags": "Tags & Allergens",
        "cook.reason.expiring": "Uses expiring ingredients",
        "cook.reason.protein": "High in protein",
        "cook.reason.allAvailable": "All ingredients available",
        "cook.reason.budget": "Budget-friendly",
        "cook.flavor.addAcidity": "Add some acidity (lemon, vinegar)",
        "cook.flavor.addSweet": "Add a touch of sweetness",
        "cook.flavor.addMoisture": "Could use more moisture",
        "cook.flavor.reduceBitter": "Reduce bitterness",
        "cook.flavor.addUmami": "Consider adding umami (soy sauce, tomato paste)",
        "cook.flavor.flat": "Dish may taste flat — add seasoning",
        "cook.cookNow": "🍳 Cook Now",
        "cook.addMissing": "🛒 Add Missing to Shopping List",
        "cook.ingredientsMissing": "ingredients missing",
        "cook.forRecipe": "For recipe",
        "cook.addedToShoppingList": "Added to shopping list!",
        "cook.nextStep": "Next",
        "cook.prevStep": "Back",
        "cook.done": "Done",
        "cook.cookingComplete": "Cooking Complete! 🎉",
        "cook.ingredientsDeducted": "Ingredients deducted from inventory",
        "cook.confirmAndDeduct": "Confirm & Deduct Ingredients",
        "cook.skipDeduction": "Skip for now",
        "cook.quitCooking": "Quit cooking?",
        "cook.quit": "Quit",
        "cook.continueCooking": "Continue cooking",

        // DishType
        "dishType.soup": "Soup", "dishType.stew": "Stew", "dishType.salad": "Salad",
        "dishType.grill": "Grill", "dishType.pasta": "Pasta", "dishType.stir_fry": "Stir Fry",
        "dishType.breakfast": "Breakfast", "dishType.snack": "Snack", "dishType.dessert": "Dessert",
        "dishType.main_course": "Main Course", "dishType.side_dish": "Side Dish",
        "dishType.default": "Dish",

        // Complexity
        "complexity.easy": "Easy", "complexity.medium": "Medium", "complexity.hard": "Hard",

        // Tags
        "tag.uses_expiring_ingredients": "Uses expiring ingredients",
        "tag.high_protein": "High protein",
        "tag.all_ingredients_available": "All ingredients available",
        "tag.budget_friendly": "Budget-friendly",
        "tag.low_calorie": "Low calorie",
        "tag.vegetarian": "Vegetarian",
        "tag.vegan": "Vegan",
        "tag.gluten_free": "Gluten-free",
        "tag.dairy_free": "Dairy-free",
        "tag.quick": "Quick",
        "tag.seasonal": "Seasonal",
        "tag.spicy": "Spicy",
        "tag.high_fiber": "High fiber",
        "tag.low_carb": "Low carb",
        "tag.high_calorie": "High calorie",

        // Allergens
        "allergen.gluten": "Gluten",
        "allergen.lactose": "Lactose",
        "allergen.nuts": "Nuts",
        "allergen.eggs": "Eggs",
        "allergen.soy": "Soy",
        "allergen.fish": "Fish",
        "allergen.shellfish": "Shellfish",
        "allergen.sesame": "Sesame",
        "allergen.celery": "Celery",
        "allergen.mustard": "Mustard",
        "allergen.milk": "Milk",
        "allergen.wheat": "Wheat",
        "allergen.peanuts": "Peanuts",

        // General
        "general.cancel": "Cancel",

        // Inventory
        "inventory.addNew": "Add to inventory",
        "inventory.addBatch": "Add another batch",
        "inventory.edit": "Edit product",
        "inventory.searchCatalog": "Search catalog to match",
        "inventory.newBatch": "New batch of existing product",
        "inventory.editCurrent": "Edit current entry",
        "inventory.details": "Product details",
        "inventory.save": "Save changes",
        "inventory.invalidQuantity": "Enter a valid quantity",
        "inventory.noMatch": "Not found in catalog",
        "inventory.notInCatalog": "\"%@\" not found in catalog",
        "inventory.addToShoppingManual": "Add \"%@\" to shopping list",
        "inventory.browseCatalog": "Browse full catalog",
        "inventory.searchPlaceholder": "Search product…",
        "inventory.existingTitle": "Product already in stock",
        "inventory.existingMessage": "%@ is already in your inventory",

        // Shopping
        "shopping.toBuy": "To buy",
        "shopping.bought": "Bought",
        "shopping.clearBought": "Clear purchased",
        "shopping.empty": "Shopping list is empty",
        "shopping.emptyHint": "Tap + on missing products in the Cook tab to add them here",
    ]
}
