//
//  LocalizationService+PL.swift
//  ChefOS
//

extension LocalizationService {
    static let pl: [String: String] = [
        "tab.chat": "Czat",
        "tab.recipes": "Przepisy",
        "tab.plan": "Plan",
        "tab.profile": "Profil",

        "profile.title": "Profil",
        "profile.personalInfo": "Dane osobowe",
        "profile.goals": "Cele",
        "profile.preferences": "Preferencje",
        "profile.restrictions": "Ograniczenia",
        "profile.lifestyle": "Styl życia",
        "profile.region": "Region",

        "profile.age": "Wiek",
        "profile.weight": "Waga (kg)",
        "profile.goal": "Cel",
        "profile.targetWeight": "Docelowa waga (kg)",
        "profile.caloriesDay": "Kalorie / dzień",
        "profile.protein": "Białko (g)",
        "profile.diet": "Dieta",
        "profile.cuisine": "Kuchnia",
        "profile.likes": "Lubię",
        "profile.dislikes": "Nie lubię",
        "profile.allergies": "Alergie",
        "profile.conditions": "Schorzenia",
        "profile.cookingLevel": "Poziom gotowania",
        "profile.cookingTime": "Czas gotowania",
        "profile.mealsDay": "Posiłków / dzień",
        "profile.country": "Kraj",
        "profile.currency": "Waluta",
        "profile.language": "Język",
        "profile.security": "Bezpieczeństwo",
        "profile.signOut": "Wyloguj",
        "profile.autoSaved": "Zapisano",
        "profile.save": "Zapisz zmiany",
        "profile.saved": "Zapisano ✓",

        "profile.aiTitle": "ChefOS rozumie Cię",
        "profile.aiSubtitle": "Na podstawie Twojego profilu",

        "tags.addLikes": "Dodaj…",
        "tags.addDislikes": "Dodaj…",
        "tags.addAllergies": "Dodaj alergię…",
        "tags.addConditions": "Dodaj schorzenie…",

        "goal.loseFat": "Schudnąć",
        "goal.gainMuscle": "Zbudować mięśnie",
        "goal.maintainWeight": "Utrzymać wagę",
        "goal.eatHealthier": "Jeść zdrowiej",
        "goal.medicalDiet": "Dieta lecznicza",

        "diet.noRestrictions": "Bez ograniczeń",
        "diet.vegetarian": "Wegetariańska",
        "diet.vegan": "Wegańska",
        "diet.keto": "Keto",
        "diet.paleo": "Paleo",
        "diet.glutenFree": "Bezglutenowa",
        "diet.dairyFree": "Bez nabiału",

        "cuisine.any": "Dowolna",
        "cuisine.asian": "Azjatycka",
        "cuisine.mediterranean": "Śródziemnomorska",
        "cuisine.american": "Amerykańska",
        "cuisine.mexican": "Meksykańska",
        "cuisine.italian": "Włoska",
        "cuisine.middleEastern": "Bliskowschodnia",

        "cooking.beginner": "Początkujący",
        "cooking.homeCook": "Domowy kucharz",
        "cooking.advanced": "Zaawansowany",
        "cooking.chef": "Szef kuchni",

        "time.quick": "≤ 15 min",
        "time.medium": "≤ 30 min",
        "time.long": "≤ 60 min",
        "time.any": "Dowolny",

        "ai.goal": "Cel",
        "ai.calories": "Kalorie",
        "ai.kcal": "kcal",
        "ai.protein": "Białko",
        "ai.g": "g",
        "ai.diet": "Dieta",
        "ai.avoid": "Unikaj",
        "ai.time": "Czas",
        "ai.level": "Poziom",

        "chat.title": "Czat",
        "chat.placeholder": "Zacznij od czegokolwiek…",
        "chat.send": "Wyślij",
        "chat.actionsLeft": "Pozostało akcji AI na dziś:",
        "chat.purchased": "kupione",
        "chat.thinking": "ChefOS myśli",
        "chat.welcome": "Cześć! Jestem Twoim asystentem ChefOS.\nCo dziś gotujemy?",
        "chat.welcomePersonal": "Cześć, {name}! 👋 Jestem Twoim osobistym asystentem ChefOS.\nZróbmy dziś coś pysznego!",
        "chat.error": "Coś poszło nie tak. Spróbuj ponownie.",
        "chat.error.network": "Brak połączenia z serwerem. Sprawdź internet i spróbuj ponownie.",
        "chat.error.server": "Serwer jest tymczasowo niedostępny. Spróbuj za chwilę.",
        "chat.error.rate_limited": "Zbyt wiele żądań. Poczekaj kilka sekund.",
        "chat.error.unauthorized": "Sesja wygasła. Zaloguj się ponownie.",
        "chat.ai": "AI",
        "chat.photo": "Zdjęcie",
        "chat.voice": "Głos",
        "chat.ingredients": "składników",
        "chat.motivation.loseWeight": "🔥 Twój cel to odchudzanie — zaproponuję lekkie, niskokaloryczne dania!",
        "chat.motivation.gainMuscle": "💪 Twój cel to budowa mięśni — skupię się na daniach bogatych w białko!",
        "chat.motivation.gainWeight": "🍖 Twój cel to przybranie na wadze — zaproponuję kaloryczne, pożywne dania!",
        "chat.motivation.eatHealthier": "🥗 Chcesz jeść zdrowiej — dobiorę zbilansowane przepisy!",
        "chat.motivation.balanced": "🎯 Utrzymajmy Twoje odżywianie zbilansowane i smaczne!",
        "chat.motivation.diet": "📋 Pamiętam Twoją dietę: {diet}. Wszystkie sugestie będą ją uwzględniać.",
        "chat.motivation.targets": "🎯 Dzienne cele: {kcal} kcal, {protein}g białka. Pomogę Ci ich trzymać!",
        "chat.motivation.allergies": "⚠️ Będę unikać: {list}. Twoje bezpieczeństwo jest najważniejsze!",

        // Chat cards (structured greeting flow)
        "chat.goal.loseWeight":    "Redukcja wagi",
        "chat.goal.gainMuscle":    "Budowanie mięśni",
        "chat.goal.gainWeight":    "Przybranie na wadze",
        "chat.goal.eatHealthier":  "Zdrowe odżywianie",
        "chat.goal.balanced":      "Zbilansowana dieta",

        "chat.focus.loseWeight":   "Fokus: lekkie, niskokaloryczne dania",
        "chat.focus.gainMuscle":   "Fokus: posiłki bogate w białko",
        "chat.focus.gainWeight":   "Fokus: kaloryczne, odżywcze dania",
        "chat.focus.eatHealthier": "Fokus: zbilansowane, zdrowe przepisy",
        "chat.focus.balanced":     "Fokus: zbilansowanie i smacznie",

        // Chat action buttons
        "chat.action.addToPlan":      "Dodaj do planu",
        "chat.action.cook":           "Zacznij gotować",
        "chat.action.swap":           "Zamień",
        "chat.action.addToCart":      "Do koszyka",
        "chat.action.addToInventory": "Do zapasów",
        "chat.action.moreInfo":       "Szczegóły",
        "chat.action.showRecipes":    "Przepisy",
        "chat.action.steps":          "kroków",
        "chat.action.added.title":    "Dodano do dzisiejszego planu",
        "chat.action.cooking.title":  "Gotowi do gotowania",
        "chat.action.shopping.title": "Dodano do listy zakupów",
        "chat.action.inventory.title": "Dodano do zapasów",
        "chat.action.swap.query":     "Zaproponuj zamiennik {ingredient} w {recipe}",
        "chat.action.showRecipes.query": "Pokaż przepisy z {product}",

        "profile.years": "lat",

        "onboarding.welcome": "Witaj w ChefOS",
        "onboarding.signIn": "Zaloguj się",
        "onboarding.signUp": "Zarejestruj się",
        "onboarding.email": "Email",
        "onboarding.password": "Hasło",
        "onboarding.name": "Twoje imię",
        "onboarding.restaurantName": "Nazwa restauracji",
        "onboarding.passwordHint": "Min. 8 znaków, co najmniej jedna litera i cyfra",
        "onboarding.noAccount": "Nie masz konta?",
        "onboarding.haveAccount": "Masz już konto?",
        "onboarding.continue": "Kontynuuj",
        "onboarding.done": "Gotowe",
        "onboarding.subtitle": "Twój asystent kulinarny AI",
        "onboarding.detecting": "Wykrywanie regionu…",
        "onboarding.currency": "Waluta:",
        "onboarding.changeCountry": "Zmień kraj",
        "onboarding.createAccount": "Utwórz konto",
        "onboarding.welcomeBack": "Witaj ponownie w ChefOS",
        "onboarding.startJourney": "Rozpocznij kulinarną podróż",
        "onboarding.kitchenName": "Nazwa Twojej kuchni",
        "onboarding.enableBiometric": "Włącz",
        "onboarding.secureAccess": "Bezpieczny dostęp do danych przez",
        "onboarding.maybeLater": "Może później",
        "onboarding.tapToUnlock": "Dotknij, aby odblokować",
        "onboarding.searchCountries": "Szukaj krajów",
        "onboarding.country": "Kraj",

        "plan.title": "Plan posiłków",
        "plan.day": "Dzień",
        "plan.week": "Tydzień",
        "plan.generationsLeft": "Pozostało generacji planu",
        "plan.resetsIn": "Reset za",
        "plan.saves": "Ten plan oszczędza",
        "plan.today": "dziś",
        "plan.overBudget": "Przekroczono budżet — Optymalizuj",
        "plan.smartPlan": "Smart Plan",
        "plan.generating": "Generowanie…",
        "plan.aiThinking": "AI myśli",
        "plan.generateAll": "Wygeneruj wszystkie posiłki",
        "plan.optimize": "Optymalizuj",
        "plan.planReady": "Plan gotowy",
        "plan.optimizedGoals": "— zoptymalizowany pod Twoje cele",
        "plan.addedTo": "Dodano do",
        "plan.weekOverview": "Przegląd tygodnia",
        "plan.meals": "posiłków",
        "plan.days": "dni",
        "plan.noMeals": "Brak zaplanowanych posiłków",
        "plan.tapGenerate": "Dotknij, aby wygenerować",
        "plan.mainMeal": "Główny posiłek",
        "plan.replace": "Zamień",
        "plan.addMeal": "Dodaj posiłek",
        "plan.tapToExpand": "Dotknij, aby rozwinąć",
        "plan.needToBuy": "Do kupienia",
        "plan.shoppingList": "Lista zakupów na dziś",
        "plan.tapToCollapse": "Dotknij, aby zwinąć",
        "plan.ingredients": "Składniki",
        "plan.steps": "Kroki",
        "plan.stepsCount": "kroków",
        "plan.breakfast": "Śniadanie",
        "plan.lunch": "Obiad",
        "plan.dinner": "Kolacja",
        "plan.kcal": "kcal",
        "plan.gProtein": "g białka",
        "plan.gP": "g B",
        "plan.gF": "g T",
        "plan.gC": "g W",
        "plan.noMealsYet": "Brak posiłków — kliknij Generuj",
        "plan.withinBudget": "W budżecie",
        "plan.overBudgetBy": "Przekroczono o %@ %@",
        "plan.hint.loadRecipes": "Ładowanie przepisów z zapasów…",
        "plan.hint.generateDay": "Kliknij Generuj, aby stworzyć plan",
        "plan.hint.balanced": "Świetny balans! Odżywianie w normie 👌",
        "plan.hint.lowProtein": "Dodaj jeszcze %@ g białka",
        "plan.hint.overCalories": "Przekroczono o %@ kcal — wybierz lżejsze",
        "plan.hint.overBudget": "Przekroczono o %@ %@ — zamień na tańsze",
        "plan.hint.emptySlots": "Jeszcze %@ posiłków do uzupełnienia",
        "plan.hint.onTrack": "Jesteś na dobrej drodze! 🎯",

        "recipes.title": "Przepisy",
        "recipes.search": "Szukaj przepisów…",
        "recipes.searchStock": "Szukaj zapasów…",
        "recipes.stock": "Zapasy",
        "recipes.cook": "Gotuj",
        "recipes.total": "Razem",
        "recipes.items": "Pozycji",
        "recipes.expiring": "Wygasa",
        "recipes.noItems": "Nie znaleziono",
        "recipes.scanReceipt": "Zeskanuj paragon w Czacie",
        "recipes.strategy": "Strategia na dziś",
        "recipes.basedOnStock": "Na podstawie zapasów",
        "recipes.canCookNow": "Można ugotować teraz",
        "recipes.canCook": "można gotować",
        "recipes.missingIngredients": "Brakujące składniki",
        "recipes.missing": "brakuje",
        "recipes.noRecipes": "Nie znaleziono przepisów",
        "recipes.cookBtn": "Gotuj",
        "recipes.cookNow": "Ugotuj teraz",
        "recipes.addToPlan": "Dodaj do planu",
        "recipes.added": "Dodano",
        "recipes.addShopping": "Dodaj do listy zakupów",
        "recipes.addMissingShopping": "Dodaj brakujące do listy",
        "recipes.showIngredients": "Pokaż składniki",
        "recipes.hideIngredients": "Ukryj składniki",
        "recipes.ingredients": "Składniki",
        "recipes.steps": "Kroki",
        "recipes.portion": "/ porcja",
        "recipes.totalCost": "razem",
        "recipes.ofBudget": "budżetu",
        "recipes.allInStock": "Wszystkie składniki na stanie",
        "recipes.missingCount": "Brakuje %d składnik(ów)",
        "recipes.cooked": "Ugotowano!",
        "recipes.stockUpdated": "Zapasy zaktualizowane",
        "recipes.addProduct": "Dodaj produkt",
        "recipes.catalogSearch": "Szukaj w katalogu…",
        "recipes.allCategories": "Wszystko",
        "recipes.quantity": "Ilość",
        "recipes.price": "Cena",
        "recipes.expiryDays": "Ważność (dni)",
        "recipes.purchaseDate": "Data zakupu",
        "recipes.expiryDate": "Najlepiej spożyć do",
        "recipes.shelfLife": "Okres przydatności",
        "recipes.addToStock": "Dodaj do zapasów",
        "recipes.adding": "Dodawanie…",
        "recipes.unit": "Jedn.",
        "recipes.calories": "kcal/100g",
        "recipes.noResults": "Nie znaleziono składników",
        "recipes.trySearch": "Spróbuj innego zapytania lub kategorii",
        "recipes.yourSettings": "Twoje ustawienia",
        "recipes.days": "dni",
        "recipes.expirestoday": "wygasa dziś",
        "recipes.daysLeft": "dn. pozostało",
        "recipes.categoryLabel": "Kategoria",
        "recipes.unitLabel": "Jednostka",
        "recipes.pricePerUnit": "Cena za jednostkę",
        "recipes.severity": "Status",
        "recipes.delete": "Usuń z zapasów",
        "recipes.filterAll": "Wszystko",
        "recipes.filterExpiring": "Wygasa",
        "recipes.filterLow": "Mało",
        "recipes.atRisk": "Zagrożone",
        "recipes.smartInsight": "Analiza",
        "recipes.insightWaste": "Potencjalne straty:",
        "recipes.insightAllGood": "Wszystkie produkty świeże!",
        "recipes.insightExpired": "przeterminowane!",
        "recipes.insightTomorrow": "wygasa jutro!",
        "recipes.insightDaysLeft": "dni — użyj najpierw",
        "recipes.whatToCook": "Co ugotować z tego?",
        "recipes.insightEmpty": "Dodaj produkty, aby uzyskać analizę",
        "recipes.insightUrgent": "%d produktów wymaga uwagi — użyj dziś",
        "recipes.insightGood": "Produkty na ~%d dni — wszystko świeże!",
        "recipes.useToday": "Użyj dziś!",
        "recipes.daysUseFirst": "dni — użyj najpierw",
        "recipes.replace": "Zamień",
        "recipes.empty": "Wolne",
        "recipes.plan": "Plan",
        "recipes.servings": "porc",
        "recipes.stepsCount": "kroków",

        "cook.title": "Co ugotować",
        "cook.favorites": "Ulubione",
        "cook.noFavorites": "Brak ulubionych przepisów",
        "cook.noFavoritesHint": "Generuj przepisy w zakładce Zapasy i dotknij ❤️ aby zapisać",
        "cook.removeFromFavorites": "Usuń z ulubionych",
        "cook.stepsNotAvailable": "Pełne kroki dostępne po otwarciu przepisu",
        "cook.perServing": "Na porcję",
        "cook.ingredients": "Składniki",
        "cook.steps": "Kroki przygotowania",
        "cook.retry": "Spróbuj ponownie",
        "cook.error": "Coś poszło nie tak",
        "cook.empty": "Dodaj więcej produktów, aby uzyskać podpowiedzi",
        "cook.emptyDescription": "Dodaj produkty do zapasów, a podpowiemy co ugotować",
        "cook.missing": "brakuje",
        "cook.openRecipe": "Otwórz przepis",
        "cook.canCookNow": "Gotowe do gotowania",
        "cook.almostReady": "Prawie gotowe",
        "cook.strategic": "Inteligentne propozycje",
        "cook.noProducts": "Brak produktów",
        "cook.noProductsHint": "Dodaj produkty do magazynu, a zaproponuję co ugotować",
        "cook.addProducts": "Dodaj produkty",
        "cook.addHint": "Dodaj przynajmniej 2–3 produkty, a zaproponuję co ugotować",
        "cook.youHave": "Masz",
        "cook.notEnough": "Za mało produktów na przepis",
        "cook.notEnoughHint": "Dodaj jeszcze kilka składników, aby odblokować przepisy",
        "cook.recommend": "Polecamy dodać",
        "cook.addProtein": "Białko (kurczak / jajka / ryba)",
        "cook.addBase": "Baza (ryż / makaron / ziemniaki)",
        "cook.addVegetable": "Warzywa (cebula / pomidor / marchew)",
        "cook.unlockHint": "+1 produkt → odblokuj propozycje przepisów",
        "cook.yourIngredients": "Twoje składniki",
        "cook.noRecipesFound": "Nie znaleziono przepisów dla twoich produktów",
        "cook.tryAddMore": "Spróbuj dodać bardziej różnorodne składniki",
        "cook.refreshSuggestions": "Odśwież propozycje",
        "cook.generateRecipes": "✨ Co ugotować z tego?",
        "cook.analysis": "Analiza",
        "cook.noProtein": "Brak białka — nie da się złożyć pełnego dania",
        "cook.hasProtein": "Białko — ✓",
        "cook.noBase": "Brak bazy (węglowodany) — nie ma z czym podać",
        "cook.hasBase": "Baza — ✓",
        "cook.noVegetable": "Brak warzyw — brakuje świeżości",
        "cook.hasVegetable": "Warzywa — ✓",
        "cook.cantCookFull": "Nie da się jeszcze złożyć pełnego dania",
        "cook.almostThere": "Prawie gotowe — jeszcze jeden typ i można gotować!",
        "cook.chicken": "Kurczak",
        "cook.eggs": "Jajka",
        "cook.fish": "Ryba",
        "cook.rice": "Ryż",
        "cook.pasta": "Makaron",
        "cook.potato": "Ziemniaki",
        "cook.onion": "Cebula",
        "cook.tomato": "Pomidor",
        "cook.carrot": "Marchew",
        "cook.recipesLocked": "Przepisy zablokowane",
        "cook.addMoreToUnlock": "Dodaj jeszcze %d produkt(ów) aby odblokować",
        "cook.tryAnyway": "✨ Spróbuj znaleźć przepis mimo to",
        "cook.browseCatalog": "Przeglądaj katalog",
        "cook.actionTitle": "Dodaj produkt",
        "cook.personalizedForYou": "Dopasowane do ciebie",
        "cook.yourGoal": "Twój cel",
        "cook.yourDiet": "Dieta",
        "cook.excluded": "Wykluczone",
        "cook.dislikesExcluded": "Nie dla ciebie",
        "cook.goal.loseWeight": "Odchudzanie",
        "cook.goal.gainMuscle": "Budowanie masy",
        "cook.goal.gainWeight": "Przybranie na wadze",
        "cook.goal.eatHealthier": "Zdrowsze odżywianie",
        "cook.goal.balanced": "Zrównoważone",
        "cook.diet.vegan": "Wegańska",
        "cook.diet.vegetarian": "Wegetariańska",
        "cook.diet.pescatarian": "Peskatariańska",
        "cook.diet.keto": "Keto",
        "cook.badge.highProtein": "Białko",
        "cook.badge.lowCal": "Lekkie",
        "cook.badge.allergenFree": "Bez alergenów",
        "cook.badge.quick": "Szybkie",
        "cook.badge.budget": "Budżet",
        "cook.reason.fitsGoal": "Pasuje do twojego celu",
        "cook.reason.usesInventory": "Z twoich produktów",
        "cook.actionMessage": "Co zrobić z %@?",
        "cook.toShoppingList": "🛒 Dodaj do listy zakupów",
        "cook.toInventory": "📦 Dodaj od razu do magazynu",
        "cook.addedFromCook": "Dodano z propozycji przepisów",
        "cook.shoppingList": "Lista zakupów",
        "cook.ingredientsCount": "Skladniki",
        "cook.daysLeft": "Dni zostalo",
        "cook.wasteRisk": "Ryzyko strat",
        "cook.unlockMore": "Odblokuj wiecej przepisów",
        "cook.tapForRecipe": "Dotknij, aby zobaczyc przepis",
        "cook.stepsCount": "kroków",
        "cook.min": "min",
        "cook.whyThisDish": "Dlaczego to danie",
        "cook.nutrition": "Wartosc odzywcza",
        "cook.perServingCount": "Na porcje",
        "cook.kcal": "kcal",
        "cook.protein": "Bialko",
        "cook.fat": "Tluszcz",
        "cook.carbs": "Weglowodany",
        "cook.flavorProfile": "Profil smakowy",
        "cook.balance": "Balans",
        "cook.dominant": "Dominujacy:",
        "cook.canImprove": "Mozna poprawic:",
        "cook.adapted": "Zoptymalizowane",
        "cook.optimizedFor": "Zoptymalizowane dla:",
        "cook.ingredientsList": "Skladniki",
        "cook.needToBuy": "Trzeba kupic",
        "cook.cookingSteps": "Kroki przygotowania",
        "cook.warnings": "Ostrzezenia",
        "cook.tags": "Tagi i alergeny",
        "cook.reason.expiring": "Wykorzystuje produkty z konczacym sie terminem",
        "cook.reason.protein": "Duzo bialka",
        "cook.reason.allAvailable": "Wszystkie skladniki dostepne",
        "cook.reason.budget": "Budzetowe",
        "cook.flavor.addAcidity": "Dodaj kwaskowosc (cytryna, ocet)",
        "cook.flavor.addSweet": "Dodaj odrobine slodyczy",
        "cook.flavor.addMoisture": "Potrzebna dodatkowa wilgoc",
        "cook.flavor.reduceBitter": "Zmniejsz goryczke",
        "cook.flavor.addUmami": "Dodaj umami (sos sojowy, pasta pomidorowa)",
        "cook.flavor.flat": "Danie moze byc mdle — dodaj przyprawy",
        "cook.cookNow": "🍳 Gotuj teraz",
        "cook.addMissing": "🛒 Dodaj brakujące do listy",
        "cook.ingredientsMissing": "brakujących składników",
        "cook.forRecipe": "Do przepisu",
        "cook.addedToShoppingList": "Dodano do listy zakupów!",
        "cook.nextStep": "Dalej",
        "cook.prevStep": "Wstecz",
        "cook.done": "Gotowe",
        "cook.cookingComplete": "Ugotowane! 🎉",
        "cook.ingredientsDeducted": "Składniki odjęte z magazynu",
        "cook.confirmAndDeduct": "Potwierdź i odejmij",
        "cook.skipDeduction": "Pomiń",
        "cook.quitCooking": "Zakończyć gotowanie?",
        "cook.quit": "Zakończ",
        "cook.continueCooking": "Kontynuuj",

        // DishType
        "dishType.soup": "Zupa", "dishType.stew": "Gulasz", "dishType.salad": "Sałatka",
        "dishType.grill": "Grill", "dishType.pasta": "Makaron", "dishType.stir_fry": "Smażone",
        "dishType.breakfast": "Śniadanie", "dishType.snack": "Przekąska", "dishType.dessert": "Deser",
        "dishType.main_course": "Danie główne", "dishType.side_dish": "Dodatek",
        "dishType.default": "Danie",

        // Complexity
        "complexity.easy": "Łatwe", "complexity.medium": "Średnie", "complexity.hard": "Trudne",

        // Tags
        "tag.uses_expiring_ingredients": "Kończący się termin",
        "tag.high_protein": "Dużo białka",
        "tag.all_ingredients_available": "Wszystko dostępne",
        "tag.budget_friendly": "Budżetowe",
        "tag.low_calorie": "Mało kalorii",
        "tag.vegetarian": "Wegetariańskie",
        "tag.vegan": "Wegańskie",
        "tag.gluten_free": "Bez glutenu",
        "tag.dairy_free": "Bez nabiału",
        "tag.quick": "Szybkie",
        "tag.seasonal": "Sezonowe",
        "tag.spicy": "Pikantne",
        "tag.high_fiber": "Dużo błonnika",
        "tag.low_carb": "Mało węglowodanów",
        "tag.high_calorie": "Wysokokaloryczne",

        // Allergens
        "allergen.gluten": "Gluten",
        "allergen.lactose": "Laktoza",
        "allergen.nuts": "Orzechy",
        "allergen.eggs": "Jajka",
        "allergen.soy": "Soja",
        "allergen.fish": "Ryba",
        "allergen.shellfish": "Owoce morza",
        "allergen.sesame": "Sezam",
        "allergen.celery": "Seler",
        "allergen.mustard": "Musztarda",
        "allergen.milk": "Mleko",
        "allergen.wheat": "Pszenica",
        "allergen.peanuts": "Orzeszki ziemne",

        "general.cancel": "Anuluj",

        "inventory.addNew": "Dodaj do magazynu",
        "inventory.addBatch": "Dodaj kolejną partię",
        "inventory.edit": "Edytuj produkt",
        "inventory.searchCatalog": "Szukaj w katalogu",
        "inventory.newBatch": "Nowa partia",
        "inventory.editCurrent": "Edytuj bieżący wpis",
        "inventory.details": "Szczegóły produktu",
        "inventory.save": "Zapisz zmiany",
        "inventory.invalidQuantity": "Podaj prawidłową ilość",
        "inventory.noMatch": "Nie znaleziono w katalogu",
        "inventory.notInCatalog": "\"%@\" nie znaleziono w katalogu",
        "inventory.addToShoppingManual": "Dodaj \"%@\" do listy zakupów",
        "inventory.browseCatalog": "Przeglądaj katalog",
        "inventory.searchPlaceholder": "Szukaj produktu…",
        "inventory.existingTitle": "Produkt jest już w magazynie",
        "inventory.existingMessage": "%@ jest już w Twoim magazynie",

        "shopping.toBuy": "Do kupienia",
        "shopping.bought": "Kupione",
        "shopping.clearBought": "Wyczyść kupione",
        "shopping.empty": "Lista zakupów jest pusta",
        "shopping.emptyHint": "Naciśnij + na brakujących produktach w zakładce Gotuj",
    ]
}
