//
//  LocalizationService+RU.swift
//  ChefOS
//

extension LocalizationService {
    static let ru: [String: String] = [
        "tab.chat": "Чат",
        "tab.recipes": "Рецепты",
        "tab.plan": "План",
        "tab.profile": "Профиль",

        "profile.title": "Профиль",
        "profile.personalInfo": "Личные данные",
        "profile.goals": "Цели",
        "profile.preferences": "Предпочтения",
        "profile.restrictions": "Ограничения",
        "profile.lifestyle": "Образ жизни",
        "profile.region": "Регион",

        "profile.age": "Возраст",
        "profile.weight": "Вес (кг)",
        "profile.goal": "Цель",
        "profile.targetWeight": "Целевой вес (кг)",
        "profile.caloriesDay": "Калории / день",
        "profile.protein": "Белок (г)",
        "profile.diet": "Диета",
        "profile.cuisine": "Кухня",
        "profile.likes": "Нравится",
        "profile.dislikes": "Не нравится",
        "profile.allergies": "Аллергии",
        "profile.conditions": "Заболевания",
        "profile.cookingLevel": "Уровень готовки",
        "profile.cookingTime": "Время готовки",
        "profile.mealsDay": "Приёмов пищи / день",
        "profile.country": "Страна",
        "profile.currency": "Валюта",
        "profile.language": "Язык",
        "profile.security": "Безопасность",
        "profile.signOut": "Выйти",
        "profile.autoSaved": "Сохранено",
        "profile.save": "Сохранить",
        "profile.saved": "Сохранено ✓",

        "profile.aiTitle": "ChefOS понимает вас",
        "profile.aiSubtitle": "На основе вашего профиля",

        "tags.addLikes": "Добавить…",
        "tags.addDislikes": "Добавить…",
        "tags.addAllergies": "Добавить аллергию…",
        "tags.addConditions": "Добавить заболевание…",

        "goal.loseFat": "Сбросить жир",
        "goal.gainMuscle": "Набрать мышцы",
        "goal.maintainWeight": "Поддерживать вес",
        "goal.eatHealthier": "Питаться правильнее",
        "goal.medicalDiet": "Лечебная диета",

        "diet.noRestrictions": "Без ограничений",
        "diet.vegetarian": "Вегетарианская",
        "diet.vegan": "Веганская",
        "diet.keto": "Кето",
        "diet.paleo": "Палео",
        "diet.glutenFree": "Без глютена",
        "diet.dairyFree": "Без молочных",

        "cuisine.any": "Любая",
        "cuisine.asian": "Азиатская",
        "cuisine.mediterranean": "Средиземноморская",
        "cuisine.american": "Американская",
        "cuisine.mexican": "Мексиканская",
        "cuisine.italian": "Итальянская",
        "cuisine.middleEastern": "Ближневосточная",

        "cooking.beginner": "Новичок",
        "cooking.homeCook": "Домашний повар",
        "cooking.advanced": "Продвинутый",
        "cooking.chef": "Шеф-повар",

        "time.quick": "≤ 15 мин",
        "time.medium": "≤ 30 мин",
        "time.long": "≤ 60 мин",
        "time.any": "Любое",

        "ai.goal": "Цель",
        "ai.calories": "Калории",
        "ai.kcal": "ккал",
        "ai.protein": "Белок",
        "ai.g": "г",
        "ai.diet": "Диета",
        "ai.avoid": "Избегать",
        "ai.time": "Время",
        "ai.level": "Уровень",

        "chat.title": "Чат",
        "chat.placeholder": "Начните с чего угодно…",
        "chat.send": "Отправить",
        "chat.actionsLeft": "ИИ-действий осталось сегодня:",
        "chat.purchased": "куплено",
        "chat.thinking": "ChefOS думает",
        "chat.welcome": "Привет! Я твой помощник ChefOS.\nЧто сегодня готовим?",
        "chat.welcomePersonal": "Привет, {name}! 👋 Я твой персональный помощник ChefOS.\nДавай сделаем сегодня вкусно!",
        "chat.error": "Не удалось связаться с сервером. Проверьте подключение.",
        "chat.ai": "ИИ",
        "chat.photo": "Фото",
        "chat.voice": "Голос",
        "chat.ingredients": "ингредиентов",
        "chat.motivation.loseWeight": "🔥 Твоя цель — похудение! Подберу лёгкие, низкокалорийные блюда!",
        "chat.motivation.gainMuscle": "💪 Твоя цель — набор мышц! Сфокусируюсь на высокобелковых блюдах!",
        "chat.motivation.gainWeight": "🍖 Твоя цель — набор веса! Предложу калорийные и питательные блюда!",
        "chat.motivation.eatHealthier": "🥗 Хочешь питаться здоровее — подберу сбалансированные рецепты!",
        "chat.motivation.balanced": "🎯 Будем держать питание сбалансированным и вкусным!",
        "chat.motivation.diet": "📋 Помню твою диету: {diet}. Все рекомендации будут её учитывать.",
        "chat.motivation.targets": "🎯 Дневные цели: {kcal} ккал, {protein}г белка. Помогу не сбиться!",
        "chat.motivation.allergies": "⚠️ Буду избегать: {list}. Твоя безопасность прежде всего!",

        // Chat cards (structured greeting flow)
        "chat.goal.loseWeight":    "Снижение веса",
        "chat.goal.gainMuscle":    "Набор мышц",
        "chat.goal.gainWeight":    "Набор веса",
        "chat.goal.eatHealthier":  "Здоровое питание",
        "chat.goal.balanced":      "Сбалансированное питание",

        "chat.focus.loseWeight":   "Фокус: лёгкие, низкокалорийные блюда",
        "chat.focus.gainMuscle":   "Фокус: высокобелковые блюда",
        "chat.focus.gainWeight":   "Фокус: питательные, калорийные блюда",
        "chat.focus.eatHealthier": "Фокус: сбалансированные, здоровые рецепты",
        "chat.focus.balanced":     "Фокус: сбалансированно и вкусно",

        "profile.years": "лет",

        "onboarding.welcome": "Добро пожаловать в ChefOS",
        "onboarding.signIn": "Войти",
        "onboarding.signUp": "Регистрация",
        "onboarding.email": "Email",
        "onboarding.password": "Пароль",
        "onboarding.name": "Ваше имя",
        "onboarding.restaurantName": "Название ресторана",
        "onboarding.passwordHint": "Мин. 8 символов, хотя бы одна буква и цифра",
        "onboarding.noAccount": "Нет аккаунта?",
        "onboarding.haveAccount": "Уже есть аккаунт?",
        "onboarding.continue": "Продолжить",
        "onboarding.done": "Готово",
        "onboarding.subtitle": "Ваш AI-помощник на кухне",
        "onboarding.detecting": "Определяем ваш регион…",
        "onboarding.currency": "Валюта:",
        "onboarding.changeCountry": "Изменить страну",
        "onboarding.createAccount": "Создать аккаунт",
        "onboarding.welcomeBack": "С возвращением в ChefOS",
        "onboarding.startJourney": "Начните кулинарное путешествие",
        "onboarding.kitchenName": "Название вашей кухни",
        "onboarding.enableBiometric": "Включить",
        "onboarding.secureAccess": "Безопасный доступ к данным через",
        "onboarding.maybeLater": "Может позже",
        "onboarding.tapToUnlock": "Нажмите для разблокировки",
        "onboarding.searchCountries": "Поиск стран",
        "onboarding.country": "Страна",

        "plan.title": "План питания",
        "plan.day": "День",
        "plan.week": "Неделя",
        "plan.generationsLeft": "Генераций плана осталось",
        "plan.resetsIn": "Сброс через",
        "plan.saves": "Этот план экономит вам",
        "plan.today": "сегодня",
        "plan.overBudget": "Превышен бюджет — Оптимизировать",
        "plan.smartPlan": "Умный план",
        "plan.generating": "Генерация…",
        "plan.aiThinking": "ИИ думает",
        "plan.generateAll": "Сгенерировать все приёмы",
        "plan.optimize": "Оптимизировать",
        "plan.planReady": "План готов",
        "plan.optimizedGoals": "— оптимизирован под ваши цели",
        "plan.addedTo": "Добавлено в",
        "plan.weekOverview": "Обзор недели",
        "plan.meals": "приёмов",
        "plan.days": "дней",
        "plan.noMeals": "Нет запланированных блюд",
        "plan.tapGenerate": "Нажмите для генерации",
        "plan.mainMeal": "Основной приём",
        "plan.replace": "Заменить",
        "plan.addMeal": "Добавить блюдо",
        "plan.tapToExpand": "Нажмите для раскрытия",
        "plan.needToBuy": "Нужно купить",
        "plan.shoppingList": "Список покупок на сегодня",
        "plan.tapToCollapse": "Нажмите для сворачивания",
        "plan.ingredients": "Ингредиенты",
        "plan.steps": "Шаги",
        "plan.stepsCount": "шагов",
        "plan.breakfast": "Завтрак",
        "plan.lunch": "Обед",
        "plan.dinner": "Ужин",
        "plan.kcal": "ккал",
        "plan.gProtein": "г белка",
        "plan.gP": "г Б",
        "plan.gF": "г Ж",
        "plan.gC": "г У",
        "plan.noMealsYet": "Пока нет блюд — нажмите Сгенерировать",
        "plan.withinBudget": "В рамках бюджета",
        "plan.overBudgetBy": "Превышение на %@ %@",
        "plan.hint.loadRecipes": "Загрузка рецептов из запасов…",
        "plan.hint.generateDay": "Нажмите Сгенерировать для создания плана",
        "plan.hint.balanced": "Отличный баланс! Питание в норме 👌",
        "plan.hint.lowProtein": "Добавьте ещё %@ г белка",
        "plan.hint.overCalories": "Превышение на %@ ккал — попробуйте легче",
        "plan.hint.overBudget": "Превышение на %@ %@ — замените дешевле",
        "plan.hint.emptySlots": "Ещё %@ приёмов пищи не заполнено",
        "plan.hint.onTrack": "Всё по плану — так держать! 🎯",

        "recipes.title": "Рецепты",
        "recipes.search": "Поиск рецептов…",
        "recipes.searchStock": "Поиск запасов…",
        "recipes.stock": "Запасы",
        "recipes.cook": "Готовить",
        "recipes.total": "Всего",
        "recipes.items": "Позиций",
        "recipes.expiring": "Истекает",
        "recipes.noItems": "Ничего не найдено",
        "recipes.scanReceipt": "Отсканируйте чек в Чате",
        "recipes.strategy": "Стратегия на сегодня",
        "recipes.basedOnStock": "На основе ваших запасов",
        "recipes.canCookNow": "Можно приготовить сейчас",
        "recipes.canCook": "можно готовить",
        "recipes.missingIngredients": "Не хватает ингредиентов",
        "recipes.missing": "не хватает",
        "recipes.noRecipes": "Рецепты не найдены",
        "recipes.cookBtn": "Готовить",
        "recipes.cookNow": "Приготовить",
        "recipes.addToPlan": "В план",
        "recipes.added": "Добавлено",
        "recipes.addShopping": "В список покупок",
        "recipes.addMissingShopping": "Добавить недостающее в список",
        "recipes.showIngredients": "Показать ингредиенты",
        "recipes.hideIngredients": "Скрыть ингредиенты",
        "recipes.ingredients": "Ингредиенты",
        "recipes.steps": "Шаги",
        "recipes.portion": "/ порция",
        "recipes.totalCost": "всего",
        "recipes.ofBudget": "от бюджета",
        "recipes.allInStock": "Все ингредиенты есть",
        "recipes.missingCount": "Не хватает %d ингредиент(ов)",
        "recipes.cooked": "Приготовлено!",
        "recipes.stockUpdated": "Запасы обновлены",
        "recipes.addProduct": "Добавить продукт",
        "recipes.catalogSearch": "Поиск в каталоге…",
        "recipes.allCategories": "Все",
        "recipes.quantity": "Количество",
        "recipes.price": "Цена",
        "recipes.expiryDays": "Срок годности (дней)",
        "recipes.addToStock": "Добавить на склад",
        "recipes.adding": "Добавляю…",
        "recipes.unit": "Ед.",
        "recipes.calories": "ккал/100г",
        "recipes.noResults": "Ингредиенты не найдены",
        "recipes.trySearch": "Попробуйте другой запрос или категорию",
        "recipes.yourSettings": "Ваши настройки",
        "recipes.days": "дней",
        "recipes.expirestoday": "истекает сегодня",
        "recipes.daysLeft": "дн. осталось",
        "recipes.categoryLabel": "Категория",
        "recipes.unitLabel": "Единица",
        "recipes.pricePerUnit": "Цена за единицу",
        "recipes.severity": "Статус",
        "recipes.delete": "Удалить со склада",
        "recipes.filterAll": "Все",
        "recipes.filterExpiring": "Истекает",
        "recipes.filterLow": "Мало",
        "recipes.atRisk": "Под угрозой",
        "recipes.smartInsight": "Умный анализ",
        "recipes.insightWaste": "Потенциальные потери:",
        "recipes.insightAllGood": "Все продукты свежие!",
        "recipes.insightExpired": "просрочено!",
        "recipes.insightTomorrow": "испортится завтра!",
        "recipes.insightDaysLeft": "дней — используй первым",
        "recipes.whatToCook": "Что приготовить из этого?",
        "recipes.insightEmpty": "Добавь продукты для умного анализа",
        "recipes.insightUrgent": "%d продуктов требуют внимания — используй сегодня",
        "recipes.insightGood": "Продуктов на ~%d дней — всё свежее!",
        "recipes.useToday": "Используй сегодня!",
        "recipes.daysUseFirst": "дн. — используй первым",
        "recipes.replace": "Заменить",
        "recipes.empty": "Свободно",
        "recipes.plan": "План",
        "recipes.servings": "порц",
        "recipes.stepsCount": "шагов",

        "cook.title": "Что приготовить",
        "cook.favorites": "Избранное",
        "cook.noFavorites": "Нет избранных рецептов",
        "cook.noFavoritesHint": "Генерируйте рецепты в разделе Запасы и нажмите ❤️ чтобы сохранить",
        "cook.removeFromFavorites": "Убрать из избранного",
        "cook.stepsNotAvailable": "Полные шаги доступны при открытии рецепта",
        "cook.perServing": "На порцию",
        "cook.ingredients": "Ингредиенты",
        "cook.steps": "Шаги приготовления",
        "cook.retry": "Попробовать снова",
        "cook.error": "Что-то пошло не так",
        "cook.empty": "Добавьте больше продуктов для подсказок",
        "cook.emptyDescription": "Добавьте продукты в запасы и мы подскажем что приготовить",
        "cook.missing": "не хватает",
        "cook.openRecipe": "Открыть рецепт",
        "cook.canCookNow": "Можно приготовить",
        "cook.almostReady": "Почти готово",
        "cook.strategic": "Умные подборки",
        "cook.noProducts": "Пока нет продуктов",
        "cook.noProductsHint": "Добавьте продукты на склад, и я предложу что приготовить",
        "cook.addProducts": "Добавить продукты",
        "cook.addHint": "Добавь хотя бы 2–3 продукта, и я предложу что приготовить",
        "cook.youHave": "У вас есть",
        "cook.notEnough": "Недостаточно продуктов для рецепта",
        "cook.notEnoughHint": "Добавьте ещё пару ингредиентов для подбора рецептов",
        "cook.recommend": "Рекомендуем добавить",
        "cook.addProtein": "Белок (курица / яйца / рыба)",
        "cook.addBase": "Основа (рис / паста / картофель)",
        "cook.addVegetable": "Овощи (лук / помидор / морковь)",
        "cook.unlockHint": "+1 продукт → откроются подборки рецептов",
        "cook.yourIngredients": "Ваши ингредиенты",
        "cook.noRecipesFound": "Рецепты для ваших продуктов не найдены",
        "cook.tryAddMore": "Попробуйте добавить разнообразнее",
        "cook.refreshSuggestions": "Обновить подборку",
        "cook.generateRecipes": "✨ Что приготовить из этого?",
        "cook.analysis": "Анализ",
        "cook.noProtein": "Нет белка — нельзя собрать полноценное блюдо",
        "cook.hasProtein": "Белок — ✓",
        "cook.noBase": "Нет основы (углеводы) — не с чем подать",
        "cook.hasBase": "Основа — ✓",
        "cook.noVegetable": "Нет овощей — не хватает свежести",
        "cook.hasVegetable": "Овощи — ✓",
        "cook.cantCookFull": "Пока нельзя собрать полноценное блюдо",
        "cook.almostThere": "Почти готово — ещё один тип и можно готовить!",
        "cook.chicken": "Курица",
        "cook.eggs": "Яйца",
        "cook.fish": "Рыба",
        "cook.rice": "Рис",
        "cook.pasta": "Паста",
        "cook.potato": "Картофель",
        "cook.onion": "Лук",
        "cook.tomato": "Помидор",
        "cook.carrot": "Морковь",
        "cook.recipesLocked": "Рецепты заблокированы",
        "cook.addMoreToUnlock": "Добавьте ещё %d продукт(ов) для разблокировки",
        "cook.tryAnyway": "✨ Попробовать найти рецепт",
        "cook.browseCatalog": "Открыть каталог",
        "cook.actionTitle": "Добавить продукт",
        "cook.personalizedForYou": "Подобрано для тебя",
        "cook.yourGoal": "Твоя цель",
        "cook.yourDiet": "Диета",
        "cook.excluded": "Исключено",
        "cook.dislikesExcluded": "Не для тебя",
        "cook.goal.loseWeight": "Похудение",
        "cook.goal.gainMuscle": "Набор мышц",
        "cook.goal.gainWeight": "Набор веса",
        "cook.goal.eatHealthier": "Здоровое питание",
        "cook.goal.balanced": "Баланс",
        "cook.diet.vegan": "Веган",
        "cook.diet.vegetarian": "Вегетарианец",
        "cook.diet.pescatarian": "Пескетарианец",
        "cook.diet.keto": "Кето",
        "cook.badge.highProtein": "Белок",
        "cook.badge.lowCal": "Лёгкое",
        "cook.badge.allergenFree": "Без аллергенов",
        "cook.badge.quick": "Быстро",
        "cook.badge.budget": "Бюджет",
        "cook.reason.fitsGoal": "Подходит под твою цель",
        "cook.reason.usesInventory": "Из твоих продуктов",
        "cook.actionMessage": "Что сделать с %@?",
        "cook.toShoppingList": "🛒 В список покупок",
        "cook.toInventory": "📦 Сразу на склад",
        "cook.addedFromCook": "Добавлено из подбора рецептов",
        "cook.shoppingList": "Список покупок",
        "cook.ingredientsCount": "Продуктов",
        "cook.daysLeft": "Дней хватит",
        "cook.wasteRisk": "Риск потерь",
        "cook.unlockMore": "Разблокируйте больше рецептов",
        "cook.tapForRecipe": "Нажмите для рецепта",
        "cook.stepsCount": "шагов",
        "cook.min": "мин",
        "cook.whyThisDish": "Почему это блюдо",
        "cook.nutrition": "Пищевая ценность",
        "cook.perServingCount": "На порцию",
        "cook.kcal": "ккал",
        "cook.protein": "Белки",
        "cook.fat": "Жиры",
        "cook.carbs": "Углеводы",
        "cook.flavorProfile": "Вкусовой профиль",
        "cook.balance": "Баланс",
        "cook.dominant": "Доминанта:",
        "cook.canImprove": "Можно улучшить:",
        "cook.adapted": "Оптимизировано",
        "cook.optimizedFor": "Оптимизировано для:",
        "cook.ingredientsList": "Ингредиенты",
        "cook.needToBuy": "Нужно купить",
        "cook.cookingSteps": "Шаги приготовления",
        "cook.warnings": "Предупреждения",
        "cook.tags": "Теги и аллергены",
        "cook.reason.expiring": "Использует продукты с истекающим сроком",
        "cook.reason.protein": "Много белка",
        "cook.reason.allAvailable": "Все ингредиенты есть",
        "cook.reason.budget": "Бюджетное",
        "cook.flavor.addAcidity": "Добавьте кислоту (лимон, уксус)",
        "cook.flavor.addSweet": "Добавьте немного сладости",
        "cook.flavor.addMoisture": "Не хватает влаги",
        "cook.flavor.reduceBitter": "Уменьшите горечь",
        "cook.flavor.addUmami": "Добавьте умами (соевый соус, томатная паста)",
        "cook.flavor.flat": "Блюдо может быть пресным — добавьте специй",
        "cook.cookNow": "🍳 Готовить",
        "cook.addMissing": "🛒 Добавить недостающее в список",
        "cook.ingredientsMissing": "ингредиентов не хватает",
        "cook.forRecipe": "Для рецепта",
        "cook.addedToShoppingList": "Добавлено в список покупок!",
        "cook.nextStep": "Далее",
        "cook.prevStep": "Назад",
        "cook.done": "Готово",
        "cook.cookingComplete": "Приготовлено! 🎉",
        "cook.ingredientsDeducted": "Ингредиенты списаны со склада",
        "cook.confirmAndDeduct": "Подтвердить и списать",
        "cook.skipDeduction": "Пропустить",
        "cook.quitCooking": "Прекратить готовку?",
        "cook.quit": "Выйти",
        "cook.continueCooking": "Продолжить",

        // DishType
        "dishType.soup": "Суп", "dishType.stew": "Рагу", "dishType.salad": "Салат",
        "dishType.grill": "Гриль", "dishType.pasta": "Паста", "dishType.stir_fry": "Жарка",
        "dishType.breakfast": "Завтрак", "dishType.snack": "Перекус", "dishType.dessert": "Десерт",
        "dishType.main_course": "Основное блюдо", "dishType.side_dish": "Гарнир",

        // Complexity
        "complexity.easy": "Легко", "complexity.medium": "Средне", "complexity.hard": "Сложно",

        // Tags
        "tag.uses_expiring_ingredients": "Истекающие продукты",
        "tag.high_protein": "Много белка",
        "tag.all_ingredients_available": "Всё есть в наличии",
        "tag.budget_friendly": "Бюджетное",
        "tag.low_calorie": "Мало калорий",
        "tag.vegetarian": "Вегетарианское",
        "tag.vegan": "Веганское",
        "tag.gluten_free": "Без глютена",
        "tag.dairy_free": "Без молока",
        "tag.quick": "Быстрое",
        "tag.seasonal": "Сезонное",
        "tag.spicy": "Острое",
        "tag.high_fiber": "Много клетчатки",
        "tag.low_carb": "Мало углеводов",
        "tag.high_calorie": "Калорийное",

        // Allergens
        "allergen.gluten": "Глютен",
        "allergen.lactose": "Лактоза",
        "allergen.nuts": "Орехи",
        "allergen.eggs": "Яйца",
        "allergen.soy": "Соя",
        "allergen.fish": "Рыба",
        "allergen.shellfish": "Морепродукты",
        "allergen.sesame": "Кунжут",
        "allergen.celery": "Сельдерей",
        "allergen.mustard": "Горчица",
        "allergen.milk": "Молоко",
        "allergen.wheat": "Пшеница",
        "allergen.peanuts": "Арахис",

        "general.cancel": "Отмена",

        "inventory.addNew": "Добавить на склад",
        "inventory.addBatch": "Добавить ещё партию",
        "inventory.edit": "Редактировать продукт",
        "inventory.searchCatalog": "Поиск в каталоге",
        "inventory.newBatch": "Новая партия",
        "inventory.editCurrent": "Изменить текущую запись",
        "inventory.details": "Данные о продукте",
        "inventory.save": "Сохранить",
        "inventory.invalidQuantity": "Введите корректное количество",
        "inventory.noMatch": "Не найдено в каталоге",
        "inventory.notInCatalog": "«%@» не найдено в каталоге",
        "inventory.addToShoppingManual": "Добавить «%@» в список покупок",
        "inventory.browseCatalog": "Открыть каталог",
        "inventory.searchPlaceholder": "Поиск продукта…",
        "inventory.existingTitle": "Продукт уже на складе",
        "inventory.existingMessage": "%@ уже есть в вашем запасе",

        "shopping.toBuy": "Купить",
        "shopping.bought": "Куплено",
        "shopping.clearBought": "Очистить купленные",
        "shopping.empty": "Список покупок пуст",
        "shopping.emptyHint": "Нажмите + на недостающих продуктах во вкладке Готовить",
    ]
}
