//
//  LocalizationService+UK.swift
//  ChefOS
//

extension LocalizationService {
    static let uk: [String: String] = [
        "tab.chat": "Чат",
        "tab.recipes": "Рецепти",
        "tab.plan": "План",
        "tab.profile": "Профіль",

        "profile.title": "Профіль",
        "profile.personalInfo": "Особисті дані",
        "profile.goals": "Цілі",
        "profile.preferences": "Вподобання",
        "profile.restrictions": "Обмеження",
        "profile.lifestyle": "Спосіб життя",
        "profile.region": "Регіон",

        "profile.age": "Вік",
        "profile.weight": "Вага (кг)",
        "profile.goal": "Ціль",
        "profile.targetWeight": "Цільова вага (кг)",
        "profile.caloriesDay": "Калорії / день",
        "profile.protein": "Білок (г)",
        "profile.diet": "Дієта",
        "profile.cuisine": "Кухня",
        "profile.likes": "Подобається",
        "profile.dislikes": "Не подобається",
        "profile.allergies": "Алергії",
        "profile.conditions": "Захворювання",
        "profile.cookingLevel": "Рівень готування",
        "profile.cookingTime": "Час готування",
        "profile.mealsDay": "Прийомів їжі / день",
        "profile.country": "Країна",
        "profile.currency": "Валюта",
        "profile.language": "Мова",
        "profile.security": "Безпека",
        "profile.signOut": "Вийти",
        "profile.autoSaved": "Збережено",
        "profile.save": "Зберегти зміни",
        "profile.saved": "Збережено ✓",

        "profile.aiTitle": "ChefOS розуміє вас",
        "profile.aiSubtitle": "На основі вашого профілю",

        "tags.addLikes": "Додати…",
        "tags.addDislikes": "Додати…",
        "tags.addAllergies": "Додати алергію…",
        "tags.addConditions": "Додати захворювання…",

        "goal.loseFat": "Скинути жир",
        "goal.gainMuscle": "Набрати м'язи",
        "goal.maintainWeight": "Підтримувати вагу",
        "goal.eatHealthier": "Їсти здоровіше",
        "goal.medicalDiet": "Лікувальна дієта",

        "diet.noRestrictions": "Без обмежень",
        "diet.vegetarian": "Вегетаріанська",
        "diet.vegan": "Веганська",
        "diet.keto": "Кето",
        "diet.paleo": "Палео",
        "diet.glutenFree": "Без глютену",
        "diet.dairyFree": "Без молочних",

        "cuisine.any": "Будь-яка",
        "cuisine.asian": "Азіатська",
        "cuisine.mediterranean": "Середземноморська",
        "cuisine.american": "Американська",
        "cuisine.mexican": "Мексиканська",
        "cuisine.italian": "Італійська",
        "cuisine.middleEastern": "Близькосхідна",

        "cooking.beginner": "Початківець",
        "cooking.homeCook": "Домашній кухар",
        "cooking.advanced": "Просунутий",
        "cooking.chef": "Шеф-кухар",

        "time.quick": "≤ 15 хв",
        "time.medium": "≤ 30 хв",
        "time.long": "≤ 60 хв",
        "time.any": "Будь-який",

        "ai.goal": "Ціль",
        "ai.calories": "Калорії",
        "ai.kcal": "ккал",
        "ai.protein": "Білок",
        "ai.g": "г",
        "ai.diet": "Дієта",
        "ai.avoid": "Уникати",
        "ai.time": "Час",
        "ai.level": "Рівень",

        "chat.title": "Чат",
        "chat.placeholder": "Почніть з будь-чого…",
        "chat.send": "Надіслати",
        "chat.actionsLeft": "ШІ-дій залишилось сьогодні:",
        "chat.purchased": "куплено",
        "chat.thinking": "ChefOS думає",
        "chat.welcome": "Привіт! Я твій помічник ChefOS.\nЩо сьогодні готуємо?",
        "chat.welcomePersonal": "Привіт, {name}! 👋 Я твій персональний помічник ChefOS.\nДавай зробимо сьогодні смачно!",
        "chat.error": "Щось пішло не так. Спробуйте ще раз.",
        "chat.error.network": "Немає зв'язку з сервером. Перевірте інтернет і спробуйте знову.",
        "chat.error.server": "Сервер тимчасово недоступний. Спробуйте за хвилину.",
        "chat.error.rate_limited": "Забагато запитів. Зачекайте кілька секунд.",
        "chat.error.unauthorized": "Сесія завершилася. Увійдіть знову.",
        "chat.ai": "ШІ",
        "chat.photo": "Фото",
        "chat.voice": "Голос",
        "chat.ingredients": "інгредієнтів",
        "chat.motivation.loseWeight": "🔥 Твоя ціль — схуднення! Підберу легкі, низькокалорійні страви!",
        "chat.motivation.gainMuscle": "💪 Твоя ціль — набір м'язів! Зосереджусь на високобілкових стравах!",
        "chat.motivation.gainWeight": "🍖 Твоя ціль — набір ваги! Запропоную калорійні та поживні страви!",
        "chat.motivation.eatHealthier": "🥗 Хочеш їсти здоровіше — підберу збалансовані рецепти!",
        "chat.motivation.balanced": "🎯 Будемо тримати харчування збалансованим та смачним!",
        "chat.motivation.diet": "📋 Пам'ятаю твою дієту: {diet}. Всі рекомендації будуть її враховувати.",
        "chat.motivation.targets": "🎯 Денні цілі: {kcal} ккал, {protein}г білка. Допоможу не збитися!",
        "chat.motivation.allergies": "⚠️ Буду уникати: {list}. Твоя безпека понад усе!",

        // Chat cards (structured greeting flow)
        "chat.goal.loseWeight":    "Схуднення",
        "chat.goal.gainMuscle":    "Набір м'язів",
        "chat.goal.gainWeight":    "Набір ваги",
        "chat.goal.eatHealthier":  "Здорове харчування",
        "chat.goal.balanced":      "Збалансоване харчування",

        "chat.focus.loseWeight":   "Фокус: легкі, низькокалорійні страви",
        "chat.focus.gainMuscle":   "Фокус: страви з високим вмістом білка",
        "chat.focus.gainWeight":   "Фокус: поживні, калорійні страви",
        "chat.focus.eatHealthier": "Фокус: збалансовані, корисні рецепти",
        "chat.focus.balanced":     "Фокус: збалансовано і смачно",

        // Chat action buttons
        "chat.action.addToPlan":      "Додати в план",
        "chat.action.cook":           "Почати готувати",
        "chat.action.swap":           "Замінити",
        "chat.action.addToCart":      "До кошика",
        "chat.action.addToInventory": "У запаси",
        "chat.action.moreInfo":       "Детальніше",
        "chat.action.showRecipes":    "Рецепти",
        "chat.action.steps":          "кроків",
        "chat.action.added.title":    "Додано в план на сьогодні",
        "chat.action.cooking.title":  "Готові готувати",
        "chat.action.shopping.title": "Додано до списку покупок",
        "chat.action.inventory.title": "Додано у запаси",
        "chat.action.swap.query":     "Запропонуй заміну для {ingredient} у {recipe}",
        "chat.action.showRecipes.query": "Покажи рецепти з {product}",

        "profile.years": "р.",

        "onboarding.welcome": "Ласкаво просимо до ChefOS",
        "onboarding.signIn": "Увійти",
        "onboarding.signUp": "Реєстрація",
        "onboarding.email": "Email",
        "onboarding.password": "Пароль",
        "onboarding.name": "Ваше ім'я",
        "onboarding.restaurantName": "Назва ресторану",
        "onboarding.passwordHint": "Мін. 8 символів, хоча б одна літера і цифра",
        "onboarding.noAccount": "Немає акаунту?",
        "onboarding.haveAccount": "Вже є акаунт?",
        "onboarding.continue": "Продовжити",
        "onboarding.done": "Готово",
        "onboarding.subtitle": "Ваш AI-помічник на кухні",
        "onboarding.detecting": "Визначаємо ваш регіон…",
        "onboarding.currency": "Валюта:",
        "onboarding.changeCountry": "Змінити країну",
        "onboarding.createAccount": "Створити акаунт",
        "onboarding.welcomeBack": "З поверненням до ChefOS",
        "onboarding.startJourney": "Почніть кулінарну подорож",
        "onboarding.kitchenName": "Назва вашої кухні",
        "onboarding.enableBiometric": "Увімкнути",
        "onboarding.secureAccess": "Безпечний доступ до даних через",
        "onboarding.maybeLater": "Може пізніше",
        "onboarding.tapToUnlock": "Торкніться для розблокування",
        "onboarding.searchCountries": "Пошук країн",
        "onboarding.country": "Країна",

        "plan.title": "План харчування",
        "plan.day": "День",
        "plan.week": "Тиждень",
        "plan.generationsLeft": "Генерацій плану залишилось",
        "plan.resetsIn": "Скидання через",
        "plan.saves": "Цей план економить вам",
        "plan.today": "сьогодні",
        "plan.overBudget": "Перевищено бюджет — Оптимізувати",
        "plan.smartPlan": "Розумний план",
        "plan.generating": "Генерація…",
        "plan.aiThinking": "ШІ думає",
        "plan.generateAll": "Згенерувати всі прийоми",
        "plan.optimize": "Оптимізувати",
        "plan.planReady": "План готовий",
        "plan.optimizedGoals": "— оптимізовано під ваші цілі",
        "plan.addedTo": "Додано до",
        "plan.weekOverview": "Огляд тижня",
        "plan.meals": "прийомів",
        "plan.days": "днів",
        "plan.noMeals": "Немає запланованих страв",
        "plan.tapGenerate": "Натисніть для генерації",
        "plan.mainMeal": "Основний прийом",
        "plan.replace": "Замінити",
        "plan.addMeal": "Додати страву",
        "plan.tapToExpand": "Натисніть для розгортання",
        "plan.needToBuy": "Потрібно купити",
        "plan.shoppingList": "Список покупок на сьогодні",
        "plan.tapToCollapse": "Натисніть для згортання",
        "plan.ingredients": "Інгредієнти",
        "plan.steps": "Кроки",
        "plan.stepsCount": "кроків",
        "plan.breakfast": "Сніданок",
        "plan.lunch": "Обід",
        "plan.dinner": "Вечеря",
        "plan.kcal": "ккал",
        "plan.gProtein": "г білка",
        "plan.gP": "г Б",
        "plan.gF": "г Ж",
        "plan.gC": "г В",
        "plan.noMealsYet": "Поки немає страв — натисніть Згенерувати",
        "plan.withinBudget": "В межах бюджету",
        "plan.overBudgetBy": "Перевищення на %@ %@",
        "plan.hint.loadRecipes": "Завантаження рецептів із запасів…",
        "plan.hint.generateDay": "Натисніть Згенерувати для створення плану",
        "plan.hint.balanced": "Чудовий баланс! Харчування в нормі 👌",
        "plan.hint.lowProtein": "Додайте ще %@ г білка",
        "plan.hint.overCalories": "Перевищення на %@ ккал — спробуйте легше",
        "plan.hint.overBudget": "Перевищення на %@ %@ — замініть дешевше",
        "plan.hint.emptySlots": "Ще %@ прийомів їжі не заповнено",
        "plan.hint.onTrack": "Все за планом — так тримати! 🎯",

        "recipes.title": "Рецепти",
        "recipes.search": "Пошук рецептів…",
        "recipes.searchStock": "Пошук запасів…",
        "recipes.stock": "Запаси",
        "recipes.cook": "Готувати",
        "recipes.total": "Всього",
        "recipes.items": "Позицій",
        "recipes.expiring": "Закінчується",
        "recipes.noItems": "Нічого не знайдено",
        "recipes.scanReceipt": "Відскануйте чек у Чаті",
        "recipes.strategy": "Стратегія на сьогодні",
        "recipes.basedOnStock": "На основі ваших запасів",
        "recipes.canCookNow": "Можна приготувати зараз",
        "recipes.canCook": "можна готувати",
        "recipes.missingIngredients": "Не вистачає інгредієнтів",
        "recipes.missing": "не вистачає",
        "recipes.noRecipes": "Рецепти не знайдено",
        "recipes.cookBtn": "Готувати",
        "recipes.cookNow": "Приготувати",
        "recipes.addToPlan": "До плану",
        "recipes.added": "Додано",
        "recipes.addShopping": "До списку покупок",
        "recipes.addMissingShopping": "Додати те, що бракує",
        "recipes.showIngredients": "Показати інгредієнти",
        "recipes.hideIngredients": "Сховати інгредієнти",
        "recipes.ingredients": "Інгредієнти",
        "recipes.steps": "Кроки",
        "recipes.portion": "/ порція",
        "recipes.totalCost": "всього",
        "recipes.ofBudget": "від бюджету",
        "recipes.allInStock": "Усі інгредієнти є",
        "recipes.missingCount": "Не вистачає %d інгредієнт(ів)",
        "recipes.cooked": "Приготовлено!",
        "recipes.stockUpdated": "Запаси оновлено",
        "recipes.addProduct": "Додати продукт",
        "recipes.catalogSearch": "Пошук у каталозі…",
        "recipes.allCategories": "Усі",
        "recipes.quantity": "Кількість",
        "recipes.price": "Ціна",
        "recipes.expiryDays": "Термін придатності (днів)",
        "recipes.addToStock": "Додати на склад",
        "recipes.adding": "Додаю…",
        "recipes.unit": "Од.",
        "recipes.calories": "ккал/100г",
        "recipes.noResults": "Інгредієнти не знайдено",
        "recipes.trySearch": "Спробуйте інший запит або категорію",
        "recipes.yourSettings": "Ваші налаштування",
        "recipes.days": "днів",
        "recipes.expirestoday": "закінчується сьогодні",
        "recipes.daysLeft": "дн. лишилось",
        "recipes.categoryLabel": "Категорія",
        "recipes.unitLabel": "Одиниця",
        "recipes.pricePerUnit": "Ціна за одиницю",
        "recipes.severity": "Статус",
        "recipes.delete": "Видалити зі складу",
        "recipes.filterAll": "Все",
        "recipes.filterExpiring": "Спливає",
        "recipes.filterLow": "Мало",
        "recipes.atRisk": "Під загрозою",
        "recipes.smartInsight": "Розумний аналіз",
        "recipes.insightWaste": "Потенційні втрати:",
        "recipes.insightAllGood": "Усі продукти свіжі!",
        "recipes.insightExpired": "прострочено!",
        "recipes.insightTomorrow": "зіпсується завтра!",
        "recipes.insightDaysLeft": "днів — використай першим",
        "recipes.whatToCook": "Що приготувати з цього?",
        "recipes.insightEmpty": "Додай продукти для розумного аналізу",
        "recipes.insightUrgent": "%d продуктів потребують уваги — використай сьогодні",
        "recipes.insightGood": "Продуктів на ~%d днів — усе свіже!",
        "recipes.useToday": "Використай сьогодні!",
        "recipes.daysUseFirst": "дн. — використай першим",
        "recipes.replace": "Замінити",
        "recipes.empty": "Вільно",
        "recipes.plan": "План",
        "recipes.servings": "порц",
        "recipes.stepsCount": "кроків",

        "cook.title": "Що приготувати",
        "cook.favorites": "Обрані",
        "cook.noFavorites": "Немає обраних рецептів",
        "cook.noFavoritesHint": "Генеруйте рецепти у розділі Запаси і натисніть ❤️ щоб зберегти",
        "cook.removeFromFavorites": "Прибрати з обраних",
        "cook.stepsNotAvailable": "Повні кроки доступні при відкритті рецепту",
        "cook.perServing": "На порцію",
        "cook.ingredients": "Інгредієнти",
        "cook.steps": "Кроки приготування",
        "cook.retry": "Спробувати знову",
        "cook.error": "Щось пішло не так",
        "cook.empty": "Додайте більше продуктів для підказок",
        "cook.emptyDescription": "Додайте продукти до запасів і ми підкажемо що приготувати",
        "cook.missing": "не вистачає",
        "cook.openRecipe": "Відкрити рецепт",
        "cook.canCookNow": "Можна приготувати",
        "cook.almostReady": "Майже готово",
        "cook.strategic": "Розумні підбірки",
        "cook.noProducts": "Поки немає продуктів",
        "cook.noProductsHint": "Додайте продукти на склад, і я запропоную що приготувати",
        "cook.addProducts": "Додати продукти",
        "cook.addHint": "Додай хоча б 2–3 продукти, і я запропоную що приготувати",
        "cook.youHave": "У вас є",
        "cook.notEnough": "Недостатньо продуктів для рецепту",
        "cook.notEnoughHint": "Додайте ще кілька інгредієнтів для підбору рецептів",
        "cook.recommend": "Рекомендуємо додати",
        "cook.addProtein": "Білок (курка / яйця / риба)",
        "cook.addBase": "Основа (рис / паста / картопля)",
        "cook.addVegetable": "Овочі (цибуля / помідор / морква)",
        "cook.unlockHint": "+1 продукт → відкриються підбірки рецептів",
        "cook.yourIngredients": "Ваші інгредієнти",
        "cook.noRecipesFound": "Рецепти для ваших продуктів не знайдені",
        "cook.tryAddMore": "Спробуйте додати різноманітніше",
        "cook.refreshSuggestions": "Оновити підбірку",
        "cook.generateRecipes": "✨ Що приготувати з цього?",
        "cook.analysis": "Аналіз",
        "cook.noProtein": "Немає білка — не можна зібрати повноцінну страву",
        "cook.hasProtein": "Білок — ✓",
        "cook.noBase": "Немає основи (вуглеводи) — нема з чим подати",
        "cook.hasBase": "Основа — ✓",
        "cook.noVegetable": "Немає овочів — бракує свіжості",
        "cook.hasVegetable": "Овочі — ✓",
        "cook.cantCookFull": "Поки не можна зібрати повноцінну страву",
        "cook.almostThere": "Майже готово — ще один тип і можна готувати!",
        "cook.chicken": "Курка",
        "cook.eggs": "Яйця",
        "cook.fish": "Риба",
        "cook.rice": "Рис",
        "cook.pasta": "Паста",
        "cook.potato": "Картопля",
        "cook.onion": "Цибуля",
        "cook.tomato": "Помідор",
        "cook.carrot": "Морква",
        "cook.recipesLocked": "Рецепти заблоковані",
        "cook.addMoreToUnlock": "Додайте ще %d продукт(ів) для розблокування",
        "cook.tryAnyway": "✨ Спробувати знайти рецепт",
        "cook.browseCatalog": "Відкрити каталог",
        "cook.actionTitle": "Додати продукт",
        "cook.personalizedForYou": "Підібрано для тебе",
        "cook.yourGoal": "Твоя ціль",
        "cook.yourDiet": "Дієта",
        "cook.excluded": "Виключено",
        "cook.dislikesExcluded": "Не для тебе",
        "cook.goal.loseWeight": "Схуднення",
        "cook.goal.gainMuscle": "Набір м'язів",
        "cook.goal.gainWeight": "Набір ваги",
        "cook.goal.eatHealthier": "Здорове харчування",
        "cook.goal.balanced": "Баланс",
        "cook.diet.vegan": "Веган",
        "cook.diet.vegetarian": "Вегетаріанець",
        "cook.diet.pescatarian": "Пескетаріанець",
        "cook.diet.keto": "Кето",
        "cook.badge.highProtein": "Білок",
        "cook.badge.lowCal": "Легке",
        "cook.badge.allergenFree": "Без алергенів",
        "cook.badge.quick": "Швидко",
        "cook.badge.budget": "Бюджет",
        "cook.reason.fitsGoal": "Підходить під твою ціль",
        "cook.reason.usesInventory": "З твоїх продуктів",
        "cook.actionMessage": "Що зробити з %@?",
        "cook.toShoppingList": "🛒 До списку покупок",
        "cook.toInventory": "📦 Одразу на склад",
        "cook.addedFromCook": "Додано з підбору рецептів",
        "cook.shoppingList": "Список покупок",
        "cook.ingredientsCount": "Продуктів",
        "cook.daysLeft": "Днів вистачить",
        "cook.wasteRisk": "Ризик втрат",
        "cook.unlockMore": "Розблокуйте більше рецептів",
        "cook.tapForRecipe": "Натисніть для рецепту",
        "cook.stepsCount": "кроків",
        "cook.min": "хв",
        "cook.whyThisDish": "Чому ця страва",
        "cook.nutrition": "Харчова цінність",
        "cook.perServingCount": "На порцію",
        "cook.kcal": "ккал",
        "cook.protein": "Білки",
        "cook.fat": "Жири",
        "cook.carbs": "Вуглеводи",
        "cook.flavorProfile": "Смаковий профіль",
        "cook.balance": "Баланс",
        "cook.dominant": "Домінанта:",
        "cook.canImprove": "Можна покращити:",
        "cook.adapted": "Оптимізовано",
        "cook.optimizedFor": "Оптимізовано для:",
        "cook.ingredientsList": "Інгредієнти",
        "cook.needToBuy": "Потрібно купити",
        "cook.cookingSteps": "Кроки приготування",
        "cook.warnings": "Попередження",
        "cook.tags": "Теги та алергени",
        "cook.reason.expiring": "Використовує продукти з терміном, що спливає",
        "cook.reason.protein": "Багато білка",
        "cook.reason.allAvailable": "Всі інгредієнти є",
        "cook.reason.budget": "Бюджетне",
        "cook.flavor.addAcidity": "Додайте кислоту (лимон, оцет)",
        "cook.flavor.addSweet": "Додайте трохи солодкості",
        "cook.flavor.addMoisture": "Не вистачає вологи",
        "cook.flavor.reduceBitter": "Зменшіть гіркоту",
        "cook.flavor.addUmami": "Додайте умамі (соєвий соус, томатна паста)",
        "cook.flavor.flat": "Страва може бути прісною — додайте спецій",
        "cook.cookNow": "🍳 Готувати",
        "cook.addMissing": "🛒 Додати відсутнє до списку",
        "cook.ingredientsMissing": "інгредієнтів не вистачає",
        "cook.forRecipe": "Для рецепту",
        "cook.addedToShoppingList": "Додано до списку покупок!",
        "cook.nextStep": "Далі",
        "cook.prevStep": "Назад",
        "cook.done": "Готово",
        "cook.cookingComplete": "Приготовлено! 🎉",
        "cook.ingredientsDeducted": "Інгредієнти списані зі складу",
        "cook.confirmAndDeduct": "Підтвердити та списати",
        "cook.skipDeduction": "Пропустити",
        "cook.quitCooking": "Припинити готування?",
        "cook.quit": "Вийти",
        "cook.continueCooking": "Продовжити",

        // DishType
        "dishType.soup": "Суп", "dishType.stew": "Рагу", "dishType.salad": "Салат",
        "dishType.grill": "Гриль", "dishType.pasta": "Паста", "dishType.stir_fry": "Смаження",
        "dishType.breakfast": "Сніданок", "dishType.snack": "Перекус", "dishType.dessert": "Десерт",
        "dishType.main_course": "Основна страва", "dishType.side_dish": "Гарнір",

        // Complexity
        "complexity.easy": "Легко", "complexity.medium": "Середнє", "complexity.hard": "Складно",

        // Tags
        "tag.uses_expiring_ingredients": "Продукти з терміном, що спливає",
        "tag.high_protein": "Багато білка",
        "tag.all_ingredients_available": "Всі інгредієнти є",
        "tag.budget_friendly": "Бюджетне",
        "tag.low_calorie": "Мало калорій",
        "tag.vegetarian": "Вегетаріанське",
        "tag.vegan": "Веганське",
        "tag.gluten_free": "Без глютену",
        "tag.dairy_free": "Без молока",
        "tag.quick": "Швидке",
        "tag.seasonal": "Сезонне",
        "tag.spicy": "Гостре",
        "tag.high_fiber": "Багато клітковини",
        "tag.low_carb": "Мало вуглеводів",
        "tag.high_calorie": "Калорійне",

        // Allergens
        "allergen.gluten": "Глютен",
        "allergen.lactose": "Лактоза",
        "allergen.nuts": "Горіхи",
        "allergen.eggs": "Яйця",
        "allergen.soy": "Соя",
        "allergen.fish": "Риба",
        "allergen.shellfish": "Морепродукти",
        "allergen.sesame": "Кунжут",
        "allergen.celery": "Селера",
        "allergen.mustard": "Гірчиця",
        "allergen.milk": "Молоко",
        "allergen.wheat": "Пшениця",
        "allergen.peanuts": "Арахіс",

        "general.cancel": "Скасувати",

        "inventory.addNew": "Додати на склад",
        "inventory.addBatch": "Додати ще партію",
        "inventory.edit": "Редагувати продукт",
        "inventory.searchCatalog": "Пошук у каталозі",
        "inventory.newBatch": "Нова партія",
        "inventory.editCurrent": "Змінити поточний запис",
        "inventory.details": "Дані про продукт",
        "inventory.save": "Зберегти",
        "inventory.invalidQuantity": "Введіть коректну кількість",
        "inventory.noMatch": "Не знайдено в каталозі",
        "inventory.notInCatalog": "«%@» не знайдено в каталозі",
        "inventory.addToShoppingManual": "Додати «%@» до списку покупок",
        "inventory.browseCatalog": "Відкрити каталог",
        "inventory.searchPlaceholder": "Пошук продукту…",
        "inventory.existingTitle": "Продукт вже на складі",
        "inventory.existingMessage": "%@ вже є у вашому запасі",

        "shopping.toBuy": "Купити",
        "shopping.bought": "Куплено",
        "shopping.clearBought": "Очистити куплені",
        "shopping.empty": "Список покупок порожній",
        "shopping.emptyHint": "Натисніть + на відсутніх продуктах у вкладці Готувати",
    ]
}
