//
//  LocalizationService.swift
//  ChefOS
//

import Foundation
import Combine
import SwiftUI

// MARK: - In-App Localization

final class LocalizationService: ObservableObject {
    @Published var language: String {
        didSet {
            UserDefaults.standard.set(language, forKey: "app_language")
        }
    }

    static let shared = LocalizationService()

    init() {
        self.language = UserDefaults.standard.string(forKey: "app_language") ?? "en"
    }

    func t(_ key: String) -> String {
        translations[language]?[key] ?? translations["en"]?[key] ?? key
    }

    // MARK: - Translations

    private let translations: [String: [String: String]] = [
        // ──────────────── English ────────────────
        "en": [
            // Tabs
            "tab.chat": "Chat",
            "tab.recipes": "Recipes",
            "tab.plan": "Plan",
            "tab.profile": "Profile",

            // Profile sections
            "profile.title": "Profile",
            "profile.personalInfo": "Personal Info",
            "profile.goals": "Goals",
            "profile.preferences": "Preferences",
            "profile.restrictions": "Restrictions",
            "profile.lifestyle": "Lifestyle",
            "profile.region": "Region",

            // Profile fields
            "profile.age": "Age",
            "profile.weight": "Weight (kg)",
            "profile.goal": "Goal",
            "profile.targetWeight": "Target weight (kg)",
            "profile.caloriesDay": "Calories / day",
            "profile.protein": "Protein (g)",
            "profile.diet": "Diet",
            "profile.cuisine": "Cuisine",
            "profile.likes": "Likes",
            "profile.dislikes": "Dislikes",
            "profile.allergies": "Allergies",
            "profile.conditions": "Conditions",
            "profile.cookingLevel": "Cooking level",
            "profile.cookingTime": "Cooking time",
            "profile.mealsDay": "Meals / day",
            "profile.country": "Country",
            "profile.currency": "Currency",
            "profile.language": "Language",
            "profile.security": "Security",
            "profile.signOut": "Sign out",
            "profile.autoSaved": "Auto-saved",

            // AI Summary
            "profile.aiTitle": "ChefOS understands you",
            "profile.aiSubtitle": "Based on your profile",

            // Tags
            "tags.addLikes": "Add likes…",
            "tags.addDislikes": "Add dislikes…",
            "tags.addAllergies": "Add allergies…",
            "tags.addConditions": "Add conditions…",

            // Fitness goals
            "goal.loseFat": "Lose fat",
            "goal.gainMuscle": "Gain muscle",
            "goal.maintainWeight": "Maintain weight",
            "goal.eatHealthier": "Eat healthier",
            "goal.medicalDiet": "Medical diet",

            // Diet types
            "diet.noRestrictions": "No restrictions",
            "diet.vegetarian": "Vegetarian",
            "diet.vegan": "Vegan",
            "diet.keto": "Keto",
            "diet.paleo": "Paleo",
            "diet.glutenFree": "Gluten-free",
            "diet.dairyFree": "Dairy-free",

            // Cuisine
            "cuisine.any": "Any",
            "cuisine.asian": "Asian",
            "cuisine.mediterranean": "Mediterranean",
            "cuisine.american": "American",
            "cuisine.mexican": "Mexican",
            "cuisine.italian": "Italian",
            "cuisine.middleEastern": "Middle Eastern",

            // Cooking level
            "cooking.beginner": "Beginner",
            "cooking.homeCook": "Home cook",
            "cooking.advanced": "Advanced",
            "cooking.chef": "Chef",

            // Cooking time
            "time.quick": "≤ 15 min",
            "time.medium": "≤ 30 min",
            "time.long": "≤ 60 min",
            "time.any": "Any",

            // AI Summary labels
            "ai.goal": "Goal",
            "ai.calories": "Calories",
            "ai.kcal": "kcal",
            "ai.protein": "Protein",
            "ai.g": "g",
            "ai.diet": "Diet",
            "ai.avoid": "Avoid",
            "ai.time": "Time",
            "ai.level": "Level",

            // Chat
            "chat.title": "Chat",
            "chat.placeholder": "Start with anything…",
            "chat.send": "Send",
            "chat.actionsLeft": "AI actions left today:",
            "chat.purchased": "purchased",
            "chat.thinking": "ChefOS is thinking",
            "chat.welcome": "Hi! I'm your ChefOS assistant.\nWhat are we cooking today?",
            "chat.error": "Sorry, I couldn't reach the server. Check your connection and try again.",
            "chat.ai": "AI",
            "chat.photo": "Photo",
            "chat.voice": "Voice",
            "chat.ingredients": "ingredients",

            // Onboarding
            "onboarding.welcome": "Welcome to ChefOS",
            "onboarding.signIn": "Sign In",
            "onboarding.signUp": "Sign Up",
            "onboarding.email": "Email",
            "onboarding.password": "Password",
            "onboarding.name": "Your name",
            "onboarding.restaurantName": "Restaurant name",
            "onboarding.passwordHint": "Min 8 characters, at least one letter and one number",
            "onboarding.noAccount": "Don't have an account?",
            "onboarding.haveAccount": "Already have an account?",
            "onboarding.continue": "Continue",
            "onboarding.done": "Done",
            "onboarding.subtitle": "Your AI cooking assistant",
            "onboarding.detecting": "Detecting your region…",
            "onboarding.currency": "Currency:",
            "onboarding.changeCountry": "Change country",
            "onboarding.createAccount": "Create Account",
            "onboarding.welcomeBack": "Welcome back to ChefOS",
            "onboarding.startJourney": "Start your cooking journey",
            "onboarding.kitchenName": "Your kitchen name",
            "onboarding.enableBiometric": "Enable",
            "onboarding.secureAccess": "Secure access to your data with",
            "onboarding.maybeLater": "Maybe later",
            "onboarding.tapToUnlock": "Tap to unlock",
            "onboarding.searchCountries": "Search countries",
            "onboarding.country": "Country",

            // Plan
            "plan.title": "Meal Plan",
            "plan.day": "Day",
            "plan.week": "Week",
            "plan.generationsLeft": "Plan generations left",
            "plan.resetsIn": "Resets in",
            "plan.saves": "This plan saves you",
            "plan.today": "today",
            "plan.overBudget": "You're over budget — Optimize now",
            "plan.smartPlan": "Smart Plan",
            "plan.generating": "Generating…",
            "plan.aiThinking": "AI is thinking",
            "plan.generateAll": "Generate all meals",
            "plan.optimize": "Optimize",
            "plan.planReady": "Plan ready",
            "plan.optimizedGoals": "— optimized for your goals",
            "plan.addedTo": "Added to",
            "plan.weekOverview": "Week Overview",
            "plan.meals": "meals",
            "plan.days": "days",
            "plan.noMeals": "No meals planned",
            "plan.tapGenerate": "Tap to generate",
            "plan.mainMeal": "Main meal",
            "plan.replace": "Replace",
            "plan.addMeal": "Add meal",
            "plan.breakfast": "Breakfast",
            "plan.lunch": "Lunch",
            "plan.dinner": "Dinner",

            // Recipes
            "recipes.title": "Recipes",
            "recipes.search": "Search recipes…",
            "recipes.searchStock": "Search stock…",
            "recipes.stock": "Stock",
            "recipes.cook": "Cook",
            "recipes.total": "Total",
            "recipes.items": "Items",
            "recipes.expiring": "Expiring",
            "recipes.noItems": "No items found",
            "recipes.scanReceipt": "Scan a receipt in Chat to add items",
            "recipes.strategy": "Strategy for today",
            "recipes.basedOnStock": "Based on your stock",
            "recipes.canCookNow": "Can cook now",
            "recipes.canCook": "can cook now",
            "recipes.missingIngredients": "Missing ingredients",
            "recipes.missing": "missing",
            "recipes.noRecipes": "No recipes found",
            "recipes.cookBtn": "Cook",
            "recipes.cookNow": "Cook now",
            "recipes.addToPlan": "Add to plan",
            "recipes.added": "Added",
            "recipes.addShopping": "Add to shopping list",
            "recipes.addMissingShopping": "Add missing to shopping list",
            "recipes.showIngredients": "Show ingredients",
            "recipes.hideIngredients": "Hide ingredients",
            "recipes.ingredients": "Ingredients",
            "recipes.steps": "Steps",
            "recipes.portion": "/ portion",
            "recipes.totalCost": "total",
            "recipes.ofBudget": "of budget",
            "recipes.allInStock": "All ingredients in stock",
            "recipes.missingCount": "Missing %d ingredient(s)",
            "recipes.cooked": "Cooked!",
            "recipes.stockUpdated": "Stock updated",
            "recipes.addProduct": "Add product",
            "recipes.catalogSearch": "Search catalog…",
            "recipes.allCategories": "All",
            "recipes.quantity": "Quantity",
            "recipes.price": "Price",
            "recipes.expiryDays": "Expires in (days)",
            "recipes.addToStock": "Add to stock",
            "recipes.adding": "Adding…",
            "recipes.unit": "Unit",
            "recipes.calories": "kcal/100g",
            "recipes.noResults": "No ingredients found",
            "recipes.trySearch": "Try a different search or category",
            "recipes.yourSettings": "Your settings",
            "recipes.days": "days",
            "recipes.expirestoday": "expires today",
            "recipes.daysLeft": "d left",
            "recipes.categoryLabel": "Category",
            "recipes.unitLabel": "Unit",
            "recipes.pricePerUnit": "Price per unit",
            "recipes.severity": "Status",
            "recipes.delete": "Remove from stock",
            "recipes.filterAll": "All",
            "recipes.filterExpiring": "Expiring",
            "recipes.filterLow": "Low",
            "recipes.atRisk": "At risk",
            "recipes.smartInsight": "Smart Insight",
            "recipes.insightWaste": "Potential losses:",
            "recipes.insightAllGood": "All products are fresh!",
            "recipes.insightExpired": "expired!",
            "recipes.insightTomorrow": "expires tomorrow!",
            "recipes.insightDaysLeft": "days left — use first",
            "recipes.whatToCook": "What to cook from this?",
            "recipes.insightEmpty": "Add products to get smart insights",
            "recipes.insightUrgent": "%d products need attention — use them today",
            "recipes.insightGood": "You have products for ~%d days — all fresh!",
            "recipes.useToday": "Use today!",
            "recipes.daysUseFirst": "days — use first",
            "cook.title": "What to Cook",
            "cook.analyzing": "Analyzing your inventory…",
            "cook.retry": "Try Again",
            "cook.empty": "Add more products to get suggestions",
            "cook.canCookNow": "Ready to Cook",
            "cook.almostReady": "Almost Ready",
            "cook.strategic": "Smart Picks",
            "cook.noProducts": "No products yet",
            "cook.noProductsHint": "Add products to your inventory and I'll suggest what to cook",
            "cook.addProducts": "Add Products",
            "cook.addHint": "Add at least 2–3 products and I'll suggest what to cook",
            "cook.youHave": "You have",
            "cook.notEnough": "Not enough products for a recipe",
            "cook.notEnoughHint": "Add a few more ingredients to unlock recipe suggestions",
            "cook.recommend": "Recommended to add",
            "cook.addProtein": "Protein (chicken / eggs / fish)",
            "cook.addBase": "Base (rice / pasta / potatoes)",
            "cook.addVegetable": "Vegetables (onion / tomato / carrot)",
            "cook.unlockHint": "+1 product → unlock recipe suggestions",
            "cook.yourIngredients": "Your ingredients",
            "cook.noRecipesFound": "No recipes found for your products",
            "cook.tryAddMore": "Try adding more diverse ingredients",
            "cook.refreshSuggestions": "Refresh suggestions",
            "cook.generateRecipes": "✨ What to cook from this?",
            "cook.analysis": "Analysis",
            "cook.noProtein": "No protein — can't build a full meal",
            "cook.hasProtein": "Protein — ✓",
            "cook.noBase": "No base (carbs) — nothing to serve with",
            "cook.hasBase": "Base — ✓",
            "cook.noVegetable": "No vegetables — missing freshness",
            "cook.hasVegetable": "Vegetables — ✓",
            "cook.cantCookFull": "Can't assemble a complete dish yet",
            "cook.almostThere": "Almost there — one more type and you're set!",
            "cook.chicken": "Chicken",
            "cook.eggs": "Eggs",
            "cook.fish": "Fish",
            "cook.rice": "Rice",
            "cook.pasta": "Pasta",
            "cook.potato": "Potato",
            "cook.onion": "Onion",
            "cook.tomato": "Tomato",
            "cook.carrot": "Carrot",
            "cook.recipesLocked": "Recipes locked",
            "cook.addMoreToUnlock": "Add %d more product(s) to unlock",
            "cook.tryAnyway": "✨ Try to find a recipe anyway",
            "cook.browseCatalog": "Browse full catalog",
            "cook.actionTitle": "Add product",
            "cook.actionMessage": "What to do with %@?",
            "cook.toShoppingList": "🛒 Add to shopping list",
            "cook.toInventory": "📦 Add to inventory",
            "cook.addedFromCook": "Added from recipe suggestions",
            "cook.shoppingList": "Shopping List",
            "cook.ingredients": "Ingredients",
            "cook.daysLeft": "Days left",
            "cook.wasteRisk": "Waste risk",
            "cook.unlockMore": "Unlock more recipes",
            "cook.tapForRecipe": "Tap for full recipe",
            "cook.steps": "steps",
            "cook.min": "min",
            "cook.whyThisDish": "Why this dish",
            "cook.nutrition": "Nutrition",
            "cook.perServing": "Per serving",
            "cook.kcal": "kcal",
            "cook.protein": "Protein",
            "cook.fat": "Fat",
            "cook.carbs": "Carbs",
            "cook.flavorProfile": "Flavor profile",
            "cook.balance": "Balance",
            "cook.dominant": "Dominant:",
            "cook.canImprove": "Can improve:",
            "cook.adapted": "Optimized",
            "cook.optimizedFor": "Optimized for:",
            "cook.ingredientsList": "Ingredients",
            "cook.needToBuy": "Need to buy",
            "cook.cookingSteps": "Cooking steps",
            "cook.warnings": "Warnings",
            "cook.tags": "Tags & Allergens",
            "cook.reason.expiring": "Uses expiring ingredients",
            "cook.reason.protein": "High in protein",
            "cook.reason.allAvailable": "All ingredients available",
            "cook.reason.budget": "Budget-friendly",
            "cook.flavor.addAcidity": "Add some acidity (lemon, vinegar)",
            "cook.flavor.addSweet": "Add a touch of sweetness",
            "cook.flavor.addMoisture": "Could use more moisture",
            "cook.flavor.reduceBitter": "Reduce bitterness",
            "cook.flavor.addUmami": "Consider adding umami (soy sauce, tomato paste)",
            "cook.flavor.flat": "Dish may taste flat — add seasoning",
            "cook.cookNow": "🍳 Cook Now",
            "cook.addMissing": "🛒 Add Missing to Shopping List",
            "cook.ingredientsMissing": "ingredients missing",
            "cook.forRecipe": "For recipe",
            "cook.addedToShoppingList": "Added to shopping list!",
            "cook.nextStep": "Next",
            "cook.prevStep": "Back",
            "cook.done": "Done",
            "cook.cookingComplete": "Cooking Complete! 🎉",
            "cook.ingredientsDeducted": "Ingredients deducted from inventory",
            "cook.confirmAndDeduct": "Confirm & Deduct Ingredients",
            "cook.skipDeduction": "Skip for now",
            "cook.quitCooking": "Quit cooking?",
            "cook.quit": "Quit",
            "cook.continueCooking": "Continue cooking",
            "general.cancel": "Cancel",
            "inventory.addNew": "Add to inventory",
            "inventory.addBatch": "Add another batch",
            "inventory.edit": "Edit product",
            "inventory.searchCatalog": "Search catalog to match",
            "inventory.newBatch": "New batch of existing product",
            "inventory.editCurrent": "Edit current entry",
            "inventory.details": "Product details",
            "inventory.save": "Save changes",
            "inventory.invalidQuantity": "Enter a valid quantity",
            "inventory.noMatch": "Not found in catalog",
            "inventory.notInCatalog": "\"%@\" not found in catalog",
            "inventory.addToShoppingManual": "Add \"%@\" to shopping list",
            "inventory.browseCatalog": "Browse full catalog",
            "inventory.searchPlaceholder": "Search product…",
            "inventory.existingTitle": "Product already in stock",
            "inventory.existingMessage": "%@ is already in your inventory",
            "shopping.toBuy": "To buy",
            "shopping.bought": "Bought",
            "shopping.clearBought": "Clear purchased",
            "shopping.empty": "Shopping list is empty",
            "shopping.emptyHint": "Tap + on missing products in the Cook tab to add them here",
            "recipes.replace": "Replace",
            "recipes.empty": "Empty",
            "recipes.plan": "Plan",
            "recipes.servings": "srv",
        ],
        "ru": [
            "tab.chat": "Чат",
            "tab.recipes": "Рецепты",
            "tab.plan": "План",
            "tab.profile": "Профиль",

            "profile.title": "Профиль",
            "profile.personalInfo": "Личные данные",
            "profile.goals": "Цели",
            "profile.preferences": "Предпочтения",
            "profile.restrictions": "Ограничения",
            "profile.lifestyle": "Образ жизни",
            "profile.region": "Регион",

            "profile.age": "Возраст",
            "profile.weight": "Вес (кг)",
            "profile.goal": "Цель",
            "profile.targetWeight": "Целевой вес (кг)",
            "profile.caloriesDay": "Калории / день",
            "profile.protein": "Белок (г)",
            "profile.diet": "Диета",
            "profile.cuisine": "Кухня",
            "profile.likes": "Нравится",
            "profile.dislikes": "Не нравится",
            "profile.allergies": "Аллергии",
            "profile.conditions": "Заболевания",
            "profile.cookingLevel": "Уровень готовки",
            "profile.cookingTime": "Время готовки",
            "profile.mealsDay": "Приёмов пищи / день",
            "profile.country": "Страна",
            "profile.currency": "Валюта",
            "profile.language": "Язык",
            "profile.security": "Безопасность",
            "profile.signOut": "Выйти",
            "profile.autoSaved": "Сохранено",

            "profile.aiTitle": "ChefOS понимает вас",
            "profile.aiSubtitle": "На основе вашего профиля",

            "tags.addLikes": "Добавить…",
            "tags.addDislikes": "Добавить…",
            "tags.addAllergies": "Добавить аллергию…",
            "tags.addConditions": "Добавить заболевание…",

            "goal.loseFat": "Сбросить жир",
            "goal.gainMuscle": "Набрать мышцы",
            "goal.maintainWeight": "Поддерживать вес",
            "goal.eatHealthier": "Питаться правильнее",
            "goal.medicalDiet": "Лечебная диета",

            "diet.noRestrictions": "Без ограничений",
            "diet.vegetarian": "Вегетарианская",
            "diet.vegan": "Веганская",
            "diet.keto": "Кето",
            "diet.paleo": "Палео",
            "diet.glutenFree": "Без глютена",
            "diet.dairyFree": "Без молочных",

            "cuisine.any": "Любая",
            "cuisine.asian": "Азиатская",
            "cuisine.mediterranean": "Средиземноморская",
            "cuisine.american": "Американская",
            "cuisine.mexican": "Мексиканская",
            "cuisine.italian": "Итальянская",
            "cuisine.middleEastern": "Ближневосточная",

            "cooking.beginner": "Новичок",
            "cooking.homeCook": "Домашний повар",
            "cooking.advanced": "Продвинутый",
            "cooking.chef": "Шеф-повар",

            "time.quick": "≤ 15 мин",
            "time.medium": "≤ 30 мин",
            "time.long": "≤ 60 мин",
            "time.any": "Любое",

            "ai.goal": "Цель",
            "ai.calories": "Калории",
            "ai.kcal": "ккал",
            "ai.protein": "Белок",
            "ai.g": "г",
            "ai.diet": "Диета",
            "ai.avoid": "Избегать",
            "ai.time": "Время",
            "ai.level": "Уровень",

            "chat.title": "Чат",
            "chat.placeholder": "Начните с чего угодно…",
            "chat.send": "Отправить",
            "chat.actionsLeft": "ИИ-действий осталось сегодня:",
            "chat.purchased": "куплено",
            "chat.thinking": "ChefOS думает",
            "chat.welcome": "Привет! Я твой помощник ChefOS.\nЧто сегодня готовим?",
            "chat.error": "Не удалось связаться с сервером. Проверьте подключение.",
            "chat.ai": "ИИ",
            "chat.photo": "Фото",
            "chat.voice": "Голос",
            "chat.ingredients": "ингредиентов",

            "onboarding.welcome": "Добро пожаловать в ChefOS",
            "onboarding.signIn": "Войти",
            "onboarding.signUp": "Регистрация",
            "onboarding.email": "Email",
            "onboarding.password": "Пароль",
            "onboarding.name": "Ваше имя",
            "onboarding.restaurantName": "Название ресторана",
            "onboarding.passwordHint": "Мин. 8 символов, хотя бы одна буква и цифра",
            "onboarding.noAccount": "Нет аккаунта?",
            "onboarding.haveAccount": "Уже есть аккаунт?",
            "onboarding.continue": "Продолжить",
            "onboarding.done": "Готово",
            "onboarding.subtitle": "Ваш AI-помощник на кухне",
            "onboarding.detecting": "Определяем ваш регион…",
            "onboarding.currency": "Валюта:",
            "onboarding.changeCountry": "Изменить страну",
            "onboarding.createAccount": "Создать аккаунт",
            "onboarding.welcomeBack": "С возвращением в ChefOS",
            "onboarding.startJourney": "Начните кулинарное путешествие",
            "onboarding.kitchenName": "Название вашей кухни",
            "onboarding.enableBiometric": "Включить",
            "onboarding.secureAccess": "Безопасный доступ к данным через",
            "onboarding.maybeLater": "Может позже",
            "onboarding.tapToUnlock": "Нажмите для разблокировки",
            "onboarding.searchCountries": "Поиск стран",
            "onboarding.country": "Страна",

            "plan.title": "План питания",
            "plan.day": "День",
            "plan.week": "Неделя",
            "plan.generationsLeft": "Генераций плана осталось",
            "plan.resetsIn": "Сброс через",
            "plan.saves": "Этот план экономит вам",
            "plan.today": "сегодня",
            "plan.overBudget": "Превышен бюджет — Оптимизировать",
            "plan.smartPlan": "Умный план",
            "plan.generating": "Генерация…",
            "plan.aiThinking": "ИИ думает",
            "plan.generateAll": "Сгенерировать все приёмы",
            "plan.optimize": "Оптимизировать",
            "plan.planReady": "План готов",
            "plan.optimizedGoals": "— оптимизирован под ваши цели",
            "plan.addedTo": "Добавлено в",
            "plan.weekOverview": "Обзор недели",
            "plan.meals": "приёмов",
            "plan.days": "дней",
            "plan.noMeals": "Нет запланированных блюд",
            "plan.tapGenerate": "Нажмите для генерации",
            "plan.mainMeal": "Основной приём",
            "plan.replace": "Заменить",
            "plan.addMeal": "Добавить блюдо",
            "plan.breakfast": "Завтрак",
            "plan.lunch": "Обед",
            "plan.dinner": "Ужин",

            "recipes.title": "Рецепты",
            "recipes.search": "Поиск рецептов…",
            "recipes.searchStock": "Поиск запасов…",
            "recipes.stock": "Запасы",
            "recipes.cook": "Готовить",
            "recipes.total": "Всего",
            "recipes.items": "Позиций",
            "recipes.expiring": "Истекает",
            "recipes.noItems": "Ничего не найдено",
            "recipes.scanReceipt": "Отсканируйте чек в Чате",
            "recipes.strategy": "Стратегия на сегодня",
            "recipes.basedOnStock": "На основе ваших запасов",
            "recipes.canCookNow": "Можно приготовить сейчас",
            "recipes.canCook": "можно готовить",
            "recipes.missingIngredients": "Не хватает ингредиентов",
            "recipes.missing": "не хватает",
            "recipes.noRecipes": "Рецепты не найдены",
            "recipes.cookBtn": "Готовить",
            "recipes.cookNow": "Приготовить",
            "recipes.addToPlan": "В план",
            "recipes.added": "Добавлено",
            "recipes.addShopping": "В список покупок",
            "recipes.addMissingShopping": "Добавить недостающее в список",
            "recipes.showIngredients": "Показать ингредиенты",
            "recipes.hideIngredients": "Скрыть ингредиенты",
            "recipes.ingredients": "Ингредиенты",
            "recipes.steps": "Шаги",
            "recipes.portion": "/ порция",
            "recipes.totalCost": "всего",
            "recipes.ofBudget": "от бюджета",
            "recipes.allInStock": "Все ингредиенты есть",
            "recipes.missingCount": "Не хватает %d ингредиент(ов)",
            "recipes.cooked": "Приготовлено!",
            "recipes.stockUpdated": "Запасы обновлены",
            "recipes.addProduct": "Добавить продукт",
            "recipes.catalogSearch": "Поиск в каталоге…",
            "recipes.allCategories": "Все",
            "recipes.quantity": "Количество",
            "recipes.price": "Цена",
            "recipes.expiryDays": "Срок годности (дней)",
            "recipes.addToStock": "Добавить на склад",
            "recipes.adding": "Добавляю…",
            "recipes.unit": "Ед.",
            "recipes.calories": "ккал/100г",
            "recipes.noResults": "Ингредиенты не найдены",
            "recipes.trySearch": "Попробуйте другой запрос или категорию",
            "recipes.yourSettings": "Ваши настройки",
            "recipes.days": "дней",
            "recipes.expirestoday": "истекает сегодня",
            "recipes.daysLeft": "дн. осталось",
            "recipes.categoryLabel": "Категория",
            "recipes.unitLabel": "Единица",
            "recipes.pricePerUnit": "Цена за единицу",
            "recipes.severity": "Статус",
            "recipes.delete": "Удалить со склада",
            "recipes.filterAll": "Все",
            "recipes.filterExpiring": "Истекает",
            "recipes.filterLow": "Мало",
            "recipes.atRisk": "Под угрозой",
            "recipes.smartInsight": "Умный анализ",
            "recipes.insightWaste": "Потенциальные потери:",
            "recipes.insightAllGood": "Все продукты свежие!",
            "recipes.insightExpired": "просрочено!",
            "recipes.insightTomorrow": "испортится завтра!",
            "recipes.insightDaysLeft": "дней — используй первым",
            "recipes.whatToCook": "Что приготовить из этого?",
            "recipes.insightEmpty": "Добавь продукты для умного анализа",
            "recipes.insightUrgent": "%d продуктов требуют внимания — используй сегодня",
            "recipes.insightGood": "Продуктов на ~%d дней — всё свежее!",
            "recipes.useToday": "Используй сегодня!",
            "recipes.daysUseFirst": "дн. — используй первым",
            "cook.title": "Что приготовить",
            "cook.analyzing": "Анализирую ваш запас…",
            "cook.retry": "Попробовать снова",
            "cook.empty": "Добавьте больше продуктов для подсказок",
            "cook.canCookNow": "Можно приготовить",
            "cook.almostReady": "Почти готово",
            "cook.strategic": "Умные подборки",
            "cook.noProducts": "Пока нет продуктов",
            "cook.noProductsHint": "Добавьте продукты на склад, и я предложу что приготовить",
            "cook.addProducts": "Добавить продукты",
            "cook.addHint": "Добавь хотя бы 2–3 продукта, и я предложу что приготовить",
            "cook.youHave": "У вас есть",
            "cook.notEnough": "Недостаточно продуктов для рецепта",
            "cook.notEnoughHint": "Добавьте ещё пару ингредиентов для подбора рецептов",
            "cook.recommend": "Рекомендуем добавить",
            "cook.addProtein": "Белок (курица / яйца / рыба)",
            "cook.addBase": "Основа (рис / паста / картофель)",
            "cook.addVegetable": "Овощи (лук / помидор / морковь)",
            "cook.unlockHint": "+1 продукт → откроются подборки рецептов",
            "cook.yourIngredients": "Ваши ингредиенты",
            "cook.noRecipesFound": "Рецепты для ваших продуктов не найдены",
            "cook.tryAddMore": "Попробуйте добавить разнообразнее",
            "cook.refreshSuggestions": "Обновить подборку",
            "cook.generateRecipes": "✨ Что приготовить из этого?",
            "cook.analysis": "Анализ",
            "cook.noProtein": "Нет белка — нельзя собрать полноценное блюдо",
            "cook.hasProtein": "Белок — ✓",
            "cook.noBase": "Нет основы (углеводы) — не с чем подать",
            "cook.hasBase": "Основа — ✓",
            "cook.noVegetable": "Нет овощей — не хватает свежести",
            "cook.hasVegetable": "Овощи — ✓",
            "cook.cantCookFull": "Пока нельзя собрать полноценное блюдо",
            "cook.almostThere": "Почти готово — ещё один тип и можно готовить!",
            "cook.chicken": "Курица",
            "cook.eggs": "Яйца",
            "cook.fish": "Рыба",
            "cook.rice": "Рис",
            "cook.pasta": "Паста",
            "cook.potato": "Картофель",
            "cook.onion": "Лук",
            "cook.tomato": "Помидор",
            "cook.carrot": "Морковь",
            "cook.recipesLocked": "Рецепты заблокированы",
            "cook.addMoreToUnlock": "Добавьте ещё %d продукт(ов) для разблокировки",
            "cook.tryAnyway": "✨ Попробовать найти рецепт",
            "cook.browseCatalog": "Открыть каталог",
            "cook.actionTitle": "Добавить продукт",
            "cook.actionMessage": "Что сделать с %@?",
            "cook.toShoppingList": "🛒 В список покупок",
            "cook.toInventory": "📦 Сразу на склад",
            "cook.addedFromCook": "Добавлено из подбора рецептов",
            "cook.shoppingList": "Список покупок",
            "cook.ingredients": "Продуктов",
            "cook.daysLeft": "Дней хватит",
            "cook.wasteRisk": "Риск потерь",
            "cook.unlockMore": "Разблокируйте больше рецептов",
            "cook.tapForRecipe": "Нажмите для рецепта",
            "cook.steps": "шагов",
            "cook.min": "мин",
            "cook.whyThisDish": "Почему это блюдо",
            "cook.nutrition": "Пищевая ценность",
            "cook.perServing": "На порцию",
            "cook.kcal": "ккал",
            "cook.protein": "Белки",
            "cook.fat": "Жиры",
            "cook.carbs": "Углеводы",
            "cook.flavorProfile": "Вкусовой профиль",
            "cook.balance": "Баланс",
            "cook.dominant": "Доминанта:",
            "cook.canImprove": "Можно улучшить:",
            "cook.adapted": "Оптимизировано",
            "cook.optimizedFor": "Оптимизировано для:",
            "cook.ingredientsList": "Ингредиенты",
            "cook.needToBuy": "Нужно купить",
            "cook.cookingSteps": "Шаги приготовления",
            "cook.warnings": "Предупреждения",
            "cook.tags": "Теги и аллергены",
            "cook.reason.expiring": "Использует продукты с истекающим сроком",
            "cook.reason.protein": "Много белка",
            "cook.reason.allAvailable": "Все ингредиенты есть",
            "cook.reason.budget": "Бюджетное",
            "cook.flavor.addAcidity": "Добавьте кислоту (лимон, уксус)",
            "cook.flavor.addSweet": "Добавьте немного сладости",
            "cook.flavor.addMoisture": "Не хватает влаги",
            "cook.flavor.reduceBitter": "Уменьшите горечь",
            "cook.flavor.addUmami": "Добавьте умами (соевый соус, томатная паста)",
            "cook.flavor.flat": "Блюдо может быть пресным — добавьте специй",
            "cook.cookNow": "🍳 Готовить",
            "cook.addMissing": "🛒 Добавить недостающее в список",
            "cook.ingredientsMissing": "ингредиентов не хватает",
            "cook.forRecipe": "Для рецепта",
            "cook.addedToShoppingList": "Добавлено в список покупок!",
            "cook.nextStep": "Далее",
            "cook.prevStep": "Назад",
            "cook.done": "Готово",
            "cook.cookingComplete": "Приготовлено! 🎉",
            "cook.ingredientsDeducted": "Ингредиенты списаны со склада",
            "cook.confirmAndDeduct": "Подтвердить и списать",
            "cook.skipDeduction": "Пропустить",
            "cook.quitCooking": "Прекратить готовку?",
            "cook.quit": "Выйти",
            "cook.continueCooking": "Продолжить",
            "general.cancel": "Отмена",
            "inventory.addNew": "Добавить на склад",
            "inventory.addBatch": "Добавить ещё партию",
            "inventory.edit": "Редактировать продукт",
            "inventory.searchCatalog": "Поиск в каталоге",
            "inventory.newBatch": "Новая партия",
            "inventory.editCurrent": "Изменить текущую запись",
            "inventory.details": "Данные о продукте",
            "inventory.save": "Сохранить",
            "inventory.invalidQuantity": "Введите корректное количество",
            "inventory.noMatch": "Не найдено в каталоге",
            "inventory.notInCatalog": "«%@» не найдено в каталоге",
            "inventory.addToShoppingManual": "Добавить «%@» в список покупок",
            "inventory.browseCatalog": "Открыть каталог",
            "inventory.searchPlaceholder": "Поиск продукта…",
            "inventory.existingTitle": "Продукт уже на складе",
            "inventory.existingMessage": "%@ уже есть в вашем запасе",
            "shopping.toBuy": "Купить",
            "shopping.bought": "Куплено",
            "shopping.clearBought": "Очистить купленные",
            "shopping.empty": "Список покупок пуст",
            "shopping.emptyHint": "Нажмите + на недостающих продуктах во вкладке Готовить",
            "recipes.replace": "Заменить",
            "recipes.empty": "Свободно",
            "recipes.plan": "План",
            "recipes.servings": "порц",
        ],
        "pl": [
            "tab.chat": "Czat",
            "tab.recipes": "Przepisy",
            "tab.plan": "Plan",
            "tab.profile": "Profil",

            "profile.title": "Profil",
            "profile.personalInfo": "Dane osobowe",
            "profile.goals": "Cele",
            "profile.preferences": "Preferencje",
            "profile.restrictions": "Ograniczenia",
            "profile.lifestyle": "Styl życia",
            "profile.region": "Region",

            "profile.age": "Wiek",
            "profile.weight": "Waga (kg)",
            "profile.goal": "Cel",
            "profile.targetWeight": "Docelowa waga (kg)",
            "profile.caloriesDay": "Kalorie / dzień",
            "profile.protein": "Białko (g)",
            "profile.diet": "Dieta",
            "profile.cuisine": "Kuchnia",
            "profile.likes": "Lubię",
            "profile.dislikes": "Nie lubię",
            "profile.allergies": "Alergie",
            "profile.conditions": "Schorzenia",
            "profile.cookingLevel": "Poziom gotowania",
            "profile.cookingTime": "Czas gotowania",
            "profile.mealsDay": "Posiłków / dzień",
            "profile.country": "Kraj",
            "profile.currency": "Waluta",
            "profile.language": "Język",
            "profile.security": "Bezpieczeństwo",
            "profile.signOut": "Wyloguj",
            "profile.autoSaved": "Zapisano",

            "profile.aiTitle": "ChefOS rozumie Cię",
            "profile.aiSubtitle": "Na podstawie Twojego profilu",

            "tags.addLikes": "Dodaj…",
            "tags.addDislikes": "Dodaj…",
            "tags.addAllergies": "Dodaj alergię…",
            "tags.addConditions": "Dodaj schorzenie…",

            "goal.loseFat": "Schudnąć",
            "goal.gainMuscle": "Zbudować mięśnie",
            "goal.maintainWeight": "Utrzymać wagę",
            "goal.eatHealthier": "Jeść zdrowiej",
            "goal.medicalDiet": "Dieta lecznicza",

            "diet.noRestrictions": "Bez ograniczeń",
            "diet.vegetarian": "Wegetariańska",
            "diet.vegan": "Wegańska",
            "diet.keto": "Keto",
            "diet.paleo": "Paleo",
            "diet.glutenFree": "Bezglutenowa",
            "diet.dairyFree": "Bez nabiału",

            "cuisine.any": "Dowolna",
            "cuisine.asian": "Azjatycka",
            "cuisine.mediterranean": "Śródziemnomorska",
            "cuisine.american": "Amerykańska",
            "cuisine.mexican": "Meksykańska",
            "cuisine.italian": "Włoska",
            "cuisine.middleEastern": "Bliskowschodnia",

            "cooking.beginner": "Początkujący",
            "cooking.homeCook": "Domowy kucharz",
            "cooking.advanced": "Zaawansowany",
            "cooking.chef": "Szef kuchni",

            "time.quick": "≤ 15 min",
            "time.medium": "≤ 30 min",
            "time.long": "≤ 60 min",
            "time.any": "Dowolny",

            "ai.goal": "Cel",
            "ai.calories": "Kalorie",
            "ai.kcal": "kcal",
            "ai.protein": "Białko",
            "ai.g": "g",
            "ai.diet": "Dieta",
            "ai.avoid": "Unikaj",
            "ai.time": "Czas",
            "ai.level": "Poziom",

            "chat.title": "Czat",
            "chat.placeholder": "Zacznij od czegokolwiek…",
            "chat.send": "Wyślij",
            "chat.actionsLeft": "Pozostało akcji AI na dziś:",
            "chat.purchased": "kupione",
            "chat.thinking": "ChefOS myśli",
            "chat.welcome": "Cześć! Jestem Twoim asystentem ChefOS.\nCo dziś gotujemy?",
            "chat.error": "Nie udało się połączyć z serwerem. Sprawdź połączenie.",
            "chat.ai": "AI",
            "chat.photo": "Zdjęcie",
            "chat.voice": "Głos",
            "chat.ingredients": "składników",

            "onboarding.welcome": "Witaj w ChefOS",
            "onboarding.signIn": "Zaloguj się",
            "onboarding.signUp": "Zarejestruj się",
            "onboarding.email": "Email",
            "onboarding.password": "Hasło",
            "onboarding.name": "Twoje imię",
            "onboarding.restaurantName": "Nazwa restauracji",
            "onboarding.passwordHint": "Min. 8 znaków, co najmniej jedna litera i cyfra",
            "onboarding.noAccount": "Nie masz konta?",
            "onboarding.haveAccount": "Masz już konto?",
            "onboarding.continue": "Kontynuuj",
            "onboarding.done": "Gotowe",
            "onboarding.subtitle": "Twój asystent kulinarny AI",
            "onboarding.detecting": "Wykrywanie regionu…",
            "onboarding.currency": "Waluta:",
            "onboarding.changeCountry": "Zmień kraj",
            "onboarding.createAccount": "Utwórz konto",
            "onboarding.welcomeBack": "Witaj ponownie w ChefOS",
            "onboarding.startJourney": "Rozpocznij kulinarną podróż",
            "onboarding.kitchenName": "Nazwa Twojej kuchni",
            "onboarding.enableBiometric": "Włącz",
            "onboarding.secureAccess": "Bezpieczny dostęp do danych przez",
            "onboarding.maybeLater": "Może później",
            "onboarding.tapToUnlock": "Dotknij, aby odblokować",
            "onboarding.searchCountries": "Szukaj krajów",
            "onboarding.country": "Kraj",

            "plan.title": "Plan posiłków",
            "plan.day": "Dzień",
            "plan.week": "Tydzień",
            "plan.generationsLeft": "Pozostało generacji planu",
            "plan.resetsIn": "Reset za",
            "plan.saves": "Ten plan oszczędza",
            "plan.today": "dziś",
            "plan.overBudget": "Przekroczono budżet — Optymalizuj",
            "plan.smartPlan": "Smart Plan",
            "plan.generating": "Generowanie…",
            "plan.aiThinking": "AI myśli",
            "plan.generateAll": "Wygeneruj wszystkie posiłki",
            "plan.optimize": "Optymalizuj",
            "plan.planReady": "Plan gotowy",
            "plan.optimizedGoals": "— zoptymalizowany pod Twoje cele",
            "plan.addedTo": "Dodano do",
            "plan.weekOverview": "Przegląd tygodnia",
            "plan.meals": "posiłków",
            "plan.days": "dni",
            "plan.noMeals": "Brak zaplanowanych posiłków",
            "plan.tapGenerate": "Dotknij, aby wygenerować",
            "plan.mainMeal": "Główny posiłek",
            "plan.replace": "Zamień",
            "plan.addMeal": "Dodaj posiłek",
            "plan.breakfast": "Śniadanie",
            "plan.lunch": "Obiad",
            "plan.dinner": "Kolacja",

            "recipes.title": "Przepisy",
            "recipes.search": "Szukaj przepisów…",
            "recipes.searchStock": "Szukaj zapasów…",
            "recipes.stock": "Zapasy",
            "recipes.cook": "Gotuj",
            "recipes.total": "Razem",
            "recipes.items": "Pozycji",
            "recipes.expiring": "Wygasa",
            "recipes.noItems": "Nie znaleziono",
            "recipes.scanReceipt": "Zeskanuj paragon w Czacie",
            "recipes.strategy": "Strategia na dziś",
            "recipes.basedOnStock": "Na podstawie zapasów",
            "recipes.canCookNow": "Można ugotować teraz",
            "recipes.canCook": "można gotować",
            "recipes.missingIngredients": "Brakujące składniki",
            "recipes.missing": "brakuje",
            "recipes.noRecipes": "Nie znaleziono przepisów",
            "recipes.cookBtn": "Gotuj",
            "recipes.cookNow": "Ugotuj teraz",
            "recipes.addToPlan": "Dodaj do planu",
            "recipes.added": "Dodano",
            "recipes.addShopping": "Dodaj do listy zakupów",
            "recipes.addMissingShopping": "Dodaj brakujące do listy",
            "recipes.showIngredients": "Pokaż składniki",
            "recipes.hideIngredients": "Ukryj składniki",
            "recipes.ingredients": "Składniki",
            "recipes.steps": "Kroki",
            "recipes.portion": "/ porcja",
            "recipes.totalCost": "razem",
            "recipes.ofBudget": "budżetu",
            "recipes.allInStock": "Wszystkie składniki na stanie",
            "recipes.missingCount": "Brakuje %d składnik(ów)",
            "recipes.cooked": "Ugotowano!",
            "recipes.stockUpdated": "Zapasy zaktualizowane",
            "recipes.addProduct": "Dodaj produkt",
            "recipes.catalogSearch": "Szukaj w katalogu…",
            "recipes.allCategories": "Wszystko",
            "recipes.quantity": "Ilość",
            "recipes.price": "Cena",
            "recipes.expiryDays": "Ważność (dni)",
            "recipes.addToStock": "Dodaj do zapasów",
            "recipes.adding": "Dodawanie…",
            "recipes.unit": "Jedn.",
            "recipes.calories": "kcal/100g",
            "recipes.noResults": "Nie znaleziono składników",
            "recipes.trySearch": "Spróbuj innego zapytania lub kategorii",
            "recipes.yourSettings": "Twoje ustawienia",
            "recipes.days": "dni",
            "recipes.expirestoday": "wygasa dziś",
            "recipes.daysLeft": "dn. pozostało",
            "recipes.categoryLabel": "Kategoria",
            "recipes.unitLabel": "Jednostka",
            "recipes.pricePerUnit": "Cena za jednostkę",
            "recipes.severity": "Status",
            "recipes.delete": "Usuń z zapasów",
            "recipes.filterAll": "Wszystko",
            "recipes.filterExpiring": "Wygasa",
            "recipes.filterLow": "Mało",
            "recipes.atRisk": "Zagrożone",
            "recipes.smartInsight": "Analiza",
            "recipes.insightWaste": "Potencjalne straty:",
            "recipes.insightAllGood": "Wszystkie produkty świeże!",
            "recipes.insightExpired": "przeterminowane!",
            "recipes.insightTomorrow": "wygasa jutro!",
            "recipes.insightDaysLeft": "dni — użyj najpierw",
            "recipes.whatToCook": "Co ugotować z tego?",
            "recipes.insightEmpty": "Dodaj produkty, aby uzyskać analizę",
            "recipes.insightUrgent": "%d produktów wymaga uwagi — użyj dziś",
            "recipes.insightGood": "Produkty na ~%d dni — wszystko świeże!",
            "recipes.useToday": "Użyj dziś!",
            "recipes.daysUseFirst": "dni — użyj najpierw",
            "cook.title": "Co ugotować",
            "cook.analyzing": "Analizuję twój zapas…",
            "cook.retry": "Spróbuj ponownie",
            "cook.empty": "Dodaj więcej produktów, aby uzyskać podpowiedzi",
            "cook.canCookNow": "Gotowe do gotowania",
            "cook.almostReady": "Prawie gotowe",
            "cook.strategic": "Inteligentne propozycje",
            "cook.noProducts": "Brak produktów",
            "cook.noProductsHint": "Dodaj produkty do magazynu, a zaproponuję co ugotować",
            "cook.addProducts": "Dodaj produkty",
            "cook.addHint": "Dodaj przynajmniej 2–3 produkty, a zaproponuję co ugotować",
            "cook.youHave": "Masz",
            "cook.notEnough": "Za mało produktów na przepis",
            "cook.notEnoughHint": "Dodaj jeszcze kilka składników, aby odblokować przepisy",
            "cook.recommend": "Polecamy dodać",
            "cook.addProtein": "Białko (kurczak / jajka / ryba)",
            "cook.addBase": "Baza (ryż / makaron / ziemniaki)",
            "cook.addVegetable": "Warzywa (cebula / pomidor / marchew)",
            "cook.unlockHint": "+1 produkt → odblokuj propozycje przepisów",
            "cook.yourIngredients": "Twoje składniki",
            "cook.noRecipesFound": "Nie znaleziono przepisów dla twoich produktów",
            "cook.tryAddMore": "Spróbuj dodać bardziej różnorodne składniki",
            "cook.refreshSuggestions": "Odśwież propozycje",
            "cook.generateRecipes": "✨ Co ugotować z tego?",
            "cook.analysis": "Analiza",
            "cook.noProtein": "Brak białka — nie da się złożyć pełnego dania",
            "cook.hasProtein": "Białko — ✓",
            "cook.noBase": "Brak bazy (węglowodany) — nie ma z czym podać",
            "cook.hasBase": "Baza — ✓",
            "cook.noVegetable": "Brak warzyw — brakuje świeżości",
            "cook.hasVegetable": "Warzywa — ✓",
            "cook.cantCookFull": "Nie da się jeszcze złożyć pełnego dania",
            "cook.almostThere": "Prawie gotowe — jeszcze jeden typ i można gotować!",
            "cook.chicken": "Kurczak",
            "cook.eggs": "Jajka",
            "cook.fish": "Ryba",
            "cook.rice": "Ryż",
            "cook.pasta": "Makaron",
            "cook.potato": "Ziemniaki",
            "cook.onion": "Cebula",
            "cook.tomato": "Pomidor",
            "cook.carrot": "Marchew",
            "cook.recipesLocked": "Przepisy zablokowane",
            "cook.addMoreToUnlock": "Dodaj jeszcze %d produkt(ów) aby odblokować",
            "cook.tryAnyway": "✨ Spróbuj znaleźć przepis mimo to",
            "cook.browseCatalog": "Przeglądaj katalog",
            "cook.actionTitle": "Dodaj produkt",
            "cook.actionMessage": "Co zrobić z %@?",
            "cook.toShoppingList": "🛒 Dodaj do listy zakupów",
            "cook.toInventory": "📦 Dodaj od razu do magazynu",
            "cook.addedFromCook": "Dodano z propozycji przepisów",
            "cook.shoppingList": "Lista zakupów",
            "cook.ingredients": "Skladniki",
            "cook.daysLeft": "Dni zostalo",
            "cook.wasteRisk": "Ryzyko strat",
            "cook.unlockMore": "Odblokuj wiecej przepisów",
            "cook.tapForRecipe": "Dotknij, aby zobaczyc przepis",
            "cook.steps": "kroków",
            "cook.min": "min",
            "cook.whyThisDish": "Dlaczego to danie",
            "cook.nutrition": "Wartosc odzywcza",
            "cook.perServing": "Na porcje",
            "cook.kcal": "kcal",
            "cook.protein": "Bialko",
            "cook.fat": "Tluszcz",
            "cook.carbs": "Weglowodany",
            "cook.flavorProfile": "Profil smakowy",
            "cook.balance": "Balans",
            "cook.dominant": "Dominujacy:",
            "cook.canImprove": "Mozna poprawic:",
            "cook.adapted": "Zoptymalizowane",
            "cook.optimizedFor": "Zoptymalizowane dla:",
            "cook.ingredientsList": "Skladniki",
            "cook.needToBuy": "Trzeba kupic",
            "cook.cookingSteps": "Kroki przygotowania",
            "cook.warnings": "Ostrzezenia",
            "cook.tags": "Tagi i alergeny",
            "cook.reason.expiring": "Wykorzystuje produkty z konczacym sie terminem",
            "cook.reason.protein": "Duzo bialka",
            "cook.reason.allAvailable": "Wszystkie skladniki dostepne",
            "cook.reason.budget": "Budzetowe",
            "cook.flavor.addAcidity": "Dodaj kwaskowosc (cytryna, ocet)",
            "cook.flavor.addSweet": "Dodaj odrobine slodyczy",
            "cook.flavor.addMoisture": "Potrzebna dodatkowa wilgoc",
            "cook.flavor.reduceBitter": "Zmniejsz goryczke",
            "cook.flavor.addUmami": "Dodaj umami (sos sojowy, pasta pomidorowa)",
            "cook.flavor.flat": "Danie moze byc mdle — dodaj przyprawy",
            "cook.cookNow": "🍳 Gotuj teraz",
            "cook.addMissing": "🛒 Dodaj brakujące do listy",
            "cook.ingredientsMissing": "brakujących składników",
            "cook.forRecipe": "Do przepisu",
            "cook.addedToShoppingList": "Dodano do listy zakupów!",
            "cook.nextStep": "Dalej",
            "cook.prevStep": "Wstecz",
            "cook.done": "Gotowe",
            "cook.cookingComplete": "Ugotowane! 🎉",
            "cook.ingredientsDeducted": "Składniki odjęte z magazynu",
            "cook.confirmAndDeduct": "Potwierdź i odejmij",
            "cook.skipDeduction": "Pomiń",
            "cook.quitCooking": "Zakończyć gotowanie?",
            "cook.quit": "Zakończ",
            "cook.continueCooking": "Kontynuuj",
            "general.cancel": "Anuluj",
            "inventory.addNew": "Dodaj do magazynu",
            "inventory.addBatch": "Dodaj kolejną partię",
            "inventory.edit": "Edytuj produkt",
            "inventory.searchCatalog": "Szukaj w katalogu",
            "inventory.newBatch": "Nowa partia",
            "inventory.editCurrent": "Edytuj bieżący wpis",
            "inventory.details": "Szczegóły produktu",
            "inventory.save": "Zapisz zmiany",
            "inventory.invalidQuantity": "Podaj prawidłową ilość",
            "inventory.noMatch": "Nie znaleziono w katalogu",
            "inventory.notInCatalog": "\"%@\" nie znaleziono w katalogu",
            "inventory.addToShoppingManual": "Dodaj \"%@\" do listy zakupów",
            "inventory.browseCatalog": "Przeglądaj katalog",
            "inventory.searchPlaceholder": "Szukaj produktu…",
            "inventory.existingTitle": "Produkt jest już w magazynie",
            "inventory.existingMessage": "%@ jest już w Twoim magazynie",
            "shopping.toBuy": "Do kupienia",
            "shopping.bought": "Kupione",
            "shopping.clearBought": "Wyczyść kupione",
            "shopping.empty": "Lista zakupów jest pusta",
            "shopping.emptyHint": "Naciśnij + na brakujących produktach w zakładce Gotuj",
            "recipes.replace": "Zamień",
            "recipes.empty": "Wolne",
            "recipes.plan": "Plan",
            "recipes.servings": "porc",
        ],
        "uk": [
            "tab.chat": "Чат",
            "tab.recipes": "Рецепти",
            "tab.plan": "План",
            "tab.profile": "Профіль",

            "profile.title": "Профіль",
            "profile.personalInfo": "Особисті дані",
            "profile.goals": "Цілі",
            "profile.preferences": "Вподобання",
            "profile.restrictions": "Обмеження",
            "profile.lifestyle": "Спосіб життя",
            "profile.region": "Регіон",

            "profile.age": "Вік",
            "profile.weight": "Вага (кг)",
            "profile.goal": "Ціль",
            "profile.targetWeight": "Цільова вага (кг)",
            "profile.caloriesDay": "Калорії / день",
            "profile.protein": "Білок (г)",
            "profile.diet": "Дієта",
            "profile.cuisine": "Кухня",
            "profile.likes": "Подобається",
            "profile.dislikes": "Не подобається",
            "profile.allergies": "Алергії",
            "profile.conditions": "Захворювання",
            "profile.cookingLevel": "Рівень готування",
            "profile.cookingTime": "Час готування",
            "profile.mealsDay": "Прийомів їжі / день",
            "profile.country": "Країна",
            "profile.currency": "Валюта",
            "profile.language": "Мова",
            "profile.security": "Безпека",
            "profile.signOut": "Вийти",
            "profile.autoSaved": "Збережено",

            "profile.aiTitle": "ChefOS розуміє вас",
            "profile.aiSubtitle": "На основі вашого профілю",

            "tags.addLikes": "Додати…",
            "tags.addDislikes": "Додати…",
            "tags.addAllergies": "Додати алергію…",
            "tags.addConditions": "Додати захворювання…",

            "goal.loseFat": "Скинути жир",
            "goal.gainMuscle": "Набрати м'язи",
            "goal.maintainWeight": "Підтримувати вагу",
            "goal.eatHealthier": "Їсти здоровіше",
            "goal.medicalDiet": "Лікувальна дієта",

            "diet.noRestrictions": "Без обмежень",
            "diet.vegetarian": "Вегетаріанська",
            "diet.vegan": "Веганська",
            "diet.keto": "Кето",
            "diet.paleo": "Палео",
            "diet.glutenFree": "Без глютену",
            "diet.dairyFree": "Без молочних",

            "cuisine.any": "Будь-яка",
            "cuisine.asian": "Азіатська",
            "cuisine.mediterranean": "Середземноморська",
            "cuisine.american": "Американська",
            "cuisine.mexican": "Мексиканська",
            "cuisine.italian": "Італійська",
            "cuisine.middleEastern": "Близькосхідна",

            "cooking.beginner": "Початківець",
            "cooking.homeCook": "Домашній кухар",
            "cooking.advanced": "Просунутий",
            "cooking.chef": "Шеф-кухар",

            "time.quick": "≤ 15 хв",
            "time.medium": "≤ 30 хв",
            "time.long": "≤ 60 хв",
            "time.any": "Будь-який",

            "ai.goal": "Ціль",
            "ai.calories": "Калорії",
            "ai.kcal": "ккал",
            "ai.protein": "Білок",
            "ai.g": "г",
            "ai.diet": "Дієта",
            "ai.avoid": "Уникати",
            "ai.time": "Час",
            "ai.level": "Рівень",

            "chat.title": "Чат",
            "chat.placeholder": "Почніть з будь-чого…",
            "chat.send": "Надіслати",
            "chat.actionsLeft": "ШІ-дій залишилось сьогодні:",
            "chat.purchased": "куплено",
            "chat.thinking": "ChefOS думає",
            "chat.welcome": "Привіт! Я твій помічник ChefOS.\nЩо сьогодні готуємо?",
            "chat.error": "Не вдалося зв'язатися з сервером. Перевірте підключення.",
            "chat.ai": "ШІ",
            "chat.photo": "Фото",
            "chat.voice": "Голос",
            "chat.ingredients": "інгредієнтів",

            "onboarding.welcome": "Ласкаво просимо до ChefOS",
            "onboarding.signIn": "Увійти",
            "onboarding.signUp": "Реєстрація",
            "onboarding.email": "Email",
            "onboarding.password": "Пароль",
            "onboarding.name": "Ваше ім'я",
            "onboarding.restaurantName": "Назва ресторану",
            "onboarding.passwordHint": "Мін. 8 символів, хоча б одна літера і цифра",
            "onboarding.noAccount": "Немає акаунту?",
            "onboarding.haveAccount": "Вже є акаунт?",
            "onboarding.continue": "Продовжити",
            "onboarding.done": "Готово",
            "onboarding.subtitle": "Ваш AI-помічник на кухні",
            "onboarding.detecting": "Визначаємо ваш регіон…",
            "onboarding.currency": "Валюта:",
            "onboarding.changeCountry": "Змінити країну",
            "onboarding.createAccount": "Створити акаунт",
            "onboarding.welcomeBack": "З поверненням до ChefOS",
            "onboarding.startJourney": "Почніть кулінарну подорож",
            "onboarding.kitchenName": "Назва вашої кухні",
            "onboarding.enableBiometric": "Увімкнути",
            "onboarding.secureAccess": "Безпечний доступ до даних через",
            "onboarding.maybeLater": "Може пізніше",
            "onboarding.tapToUnlock": "Торкніться для розблокування",
            "onboarding.searchCountries": "Пошук країн",
            "onboarding.country": "Країна",

            "plan.title": "План харчування",
            "plan.day": "День",
            "plan.week": "Тиждень",
            "plan.generationsLeft": "Генерацій плану залишилось",
            "plan.resetsIn": "Скидання через",
            "plan.saves": "Цей план економить вам",
            "plan.today": "сьогодні",
            "plan.overBudget": "Перевищено бюджет — Оптимізувати",
            "plan.smartPlan": "Розумний план",
            "plan.generating": "Генерація…",
            "plan.aiThinking": "ШІ думає",
            "plan.generateAll": "Згенерувати всі прийоми",
            "plan.optimize": "Оптимізувати",
            "plan.planReady": "План готовий",
            "plan.optimizedGoals": "— оптимізовано під ваші цілі",
            "plan.addedTo": "Додано до",
            "plan.weekOverview": "Огляд тижня",
            "plan.meals": "прийомів",
            "plan.days": "днів",
            "plan.noMeals": "Немає запланованих страв",
            "plan.tapGenerate": "Натисніть для генерації",
            "plan.mainMeal": "Основний прийом",
            "plan.replace": "Замінити",
            "plan.addMeal": "Додати страву",
            "plan.breakfast": "Сніданок",
            "plan.lunch": "Обід",
            "plan.dinner": "Вечеря",

            "recipes.title": "Рецепти",
            "recipes.search": "Пошук рецептів…",
            "recipes.searchStock": "Пошук запасів…",
            "recipes.stock": "Запаси",
            "recipes.cook": "Готувати",
            "recipes.total": "Всього",
            "recipes.items": "Позицій",
            "recipes.expiring": "Закінчується",
            "recipes.noItems": "Нічого не знайдено",
            "recipes.scanReceipt": "Відскануйте чек у Чаті",
            "recipes.strategy": "Стратегія на сьогодні",
            "recipes.basedOnStock": "На основі ваших запасів",
            "recipes.canCookNow": "Можна приготувати зараз",
            "recipes.canCook": "можна готувати",
            "recipes.missingIngredients": "Не вистачає інгредієнтів",
            "recipes.missing": "не вистачає",
            "recipes.noRecipes": "Рецепти не знайдено",
            "recipes.cookBtn": "Готувати",
            "recipes.cookNow": "Приготувати",
            "recipes.addToPlan": "До плану",
            "recipes.added": "Додано",
            "recipes.addShopping": "До списку покупок",
            "recipes.addMissingShopping": "Додати те, що бракує",
            "recipes.showIngredients": "Показати інгредієнти",
            "recipes.hideIngredients": "Сховати інгредієнти",
            "recipes.ingredients": "Інгредієнти",
            "recipes.steps": "Кроки",
            "recipes.portion": "/ порція",
            "recipes.totalCost": "всього",
            "recipes.ofBudget": "від бюджету",
            "recipes.allInStock": "Усі інгредієнти є",
            "recipes.missingCount": "Не вистачає %d інгредієнт(ів)",
            "recipes.cooked": "Приготовлено!",
            "recipes.stockUpdated": "Запаси оновлено",
            "recipes.addProduct": "Додати продукт",
            "recipes.catalogSearch": "Пошук у каталозі…",
            "recipes.allCategories": "Усі",
            "recipes.quantity": "Кількість",
            "recipes.price": "Ціна",
            "recipes.expiryDays": "Термін придатності (днів)",
            "recipes.addToStock": "Додати на склад",
            "recipes.adding": "Додаю…",
            "recipes.unit": "Од.",
            "recipes.calories": "ккал/100г",
            "recipes.noResults": "Інгредієнти не знайдено",
            "recipes.trySearch": "Спробуйте інший запит або категорію",
            "recipes.yourSettings": "Ваші налаштування",
            "recipes.days": "днів",
            "recipes.expirestoday": "закінчується сьогодні",
            "recipes.daysLeft": "дн. лишилось",
            "recipes.categoryLabel": "Категорія",
            "recipes.unitLabel": "Одиниця",
            "recipes.pricePerUnit": "Ціна за одиницю",
            "recipes.severity": "Статус",
            "recipes.delete": "Видалити зі складу",
            "recipes.filterAll": "Все",
            "recipes.filterExpiring": "Спливає",
            "recipes.filterLow": "Мало",
            "recipes.atRisk": "Під загрозою",
            "recipes.smartInsight": "Розумний аналіз",
            "recipes.insightWaste": "Потенційні втрати:",
            "recipes.insightAllGood": "Усі продукти свіжі!",
            "recipes.insightExpired": "прострочено!",
            "recipes.insightTomorrow": "зіпсується завтра!",
            "recipes.insightDaysLeft": "днів — використай першим",
            "recipes.whatToCook": "Що приготувати з цього?",
            "recipes.insightEmpty": "Додай продукти для розумного аналізу",
            "recipes.insightUrgent": "%d продуктів потребують уваги — використай сьогодні",
            "recipes.insightGood": "Продуктів на ~%d днів — усе свіже!",
            "recipes.useToday": "Використай сьогодні!",
            "recipes.daysUseFirst": "дн. — використай першим",
            "cook.title": "Що приготувати",
            "cook.analyzing": "Аналізую ваш запас…",
            "cook.retry": "Спробувати знову",
            "cook.empty": "Додайте більше продуктів для підказок",
            "cook.canCookNow": "Можна приготувати",
            "cook.almostReady": "Майже готово",
            "cook.strategic": "Розумні підбірки",
            "cook.noProducts": "Поки немає продуктів",
            "cook.noProductsHint": "Додайте продукти на склад, і я запропоную що приготувати",
            "cook.addProducts": "Додати продукти",
            "cook.addHint": "Додай хоча б 2–3 продукти, і я запропоную що приготувати",
            "cook.youHave": "У вас є",
            "cook.notEnough": "Недостатньо продуктів для рецепту",
            "cook.notEnoughHint": "Додайте ще кілька інгредієнтів для підбору рецептів",
            "cook.recommend": "Рекомендуємо додати",
            "cook.addProtein": "Білок (курка / яйця / риба)",
            "cook.addBase": "Основа (рис / паста / картопля)",
            "cook.addVegetable": "Овочі (цибуля / помідор / морква)",
            "cook.unlockHint": "+1 продукт → відкриються підбірки рецептів",
            "cook.yourIngredients": "Ваші інгредієнти",
            "cook.noRecipesFound": "Рецепти для ваших продуктів не знайдені",
            "cook.tryAddMore": "Спробуйте додати різноманітніше",
            "cook.refreshSuggestions": "Оновити підбірку",
            "cook.generateRecipes": "✨ Що приготувати з цього?",
            "cook.analysis": "Аналіз",
            "cook.noProtein": "Немає білка — не можна зібрати повноцінну страву",
            "cook.hasProtein": "Білок — ✓",
            "cook.noBase": "Немає основи (вуглеводи) — нема з чим подати",
            "cook.hasBase": "Основа — ✓",
            "cook.noVegetable": "Немає овочів — бракує свіжості",
            "cook.hasVegetable": "Овочі — ✓",
            "cook.cantCookFull": "Поки не можна зібрати повноцінну страву",
            "cook.almostThere": "Майже готово — ще один тип і можна готувати!",
            "cook.chicken": "Курка",
            "cook.eggs": "Яйця",
            "cook.fish": "Риба",
            "cook.rice": "Рис",
            "cook.pasta": "Паста",
            "cook.potato": "Картопля",
            "cook.onion": "Цибуля",
            "cook.tomato": "Помідор",
            "cook.carrot": "Морква",
            "cook.recipesLocked": "Рецепти заблоковані",
            "cook.addMoreToUnlock": "Додайте ще %d продукт(ів) для розблокування",
            "cook.tryAnyway": "✨ Спробувати знайти рецепт",
            "cook.browseCatalog": "Відкрити каталог",
            "cook.actionTitle": "Додати продукт",
            "cook.actionMessage": "Що зробити з %@?",
            "cook.toShoppingList": "🛒 До списку покупок",
            "cook.toInventory": "📦 Одразу на склад",
            "cook.addedFromCook": "Додано з підбору рецептів",
            "cook.shoppingList": "Список покупок",
            "cook.ingredients": "Продуктів",
            "cook.daysLeft": "Днів вистачить",
            "cook.wasteRisk": "Ризик втрат",
            "cook.unlockMore": "Розблокуйте більше рецептів",
            "cook.tapForRecipe": "Натисніть для рецепту",
            "cook.steps": "кроків",
            "cook.min": "хв",
            "cook.whyThisDish": "Чому ця страва",
            "cook.nutrition": "Харчова цінність",
            "cook.perServing": "На порцію",
            "cook.kcal": "ккал",
            "cook.protein": "Білки",
            "cook.fat": "Жири",
            "cook.carbs": "Вуглеводи",
            "cook.flavorProfile": "Смаковий профіль",
            "cook.balance": "Баланс",
            "cook.dominant": "Домінанта:",
            "cook.canImprove": "Можна покращити:",
            "cook.adapted": "Оптимізовано",
            "cook.optimizedFor": "Оптимізовано для:",
            "cook.ingredientsList": "Інгредієнти",
            "cook.needToBuy": "Потрібно купити",
            "cook.cookingSteps": "Кроки приготування",
            "cook.warnings": "Попередження",
            "cook.tags": "Теги та алергени",
            "cook.reason.expiring": "Використовує продукти з терміном, що спливає",
            "cook.reason.protein": "Багато білка",
            "cook.reason.allAvailable": "Всі інгредієнти є",
            "cook.reason.budget": "Бюджетне",
            "cook.flavor.addAcidity": "Додайте кислоту (лимон, оцет)",
            "cook.flavor.addSweet": "Додайте трохи солодкості",
            "cook.flavor.addMoisture": "Не вистачає вологи",
            "cook.flavor.reduceBitter": "Зменшіть гіркоту",
            "cook.flavor.addUmami": "Додайте умамі (соєвий соус, томатна паста)",
            "cook.flavor.flat": "Страва може бути прісною — додайте спецій",
            "cook.cookNow": "🍳 Готувати",
            "cook.addMissing": "🛒 Додати відсутнє до списку",
            "cook.ingredientsMissing": "інгредієнтів не вистачає",
            "cook.forRecipe": "Для рецепту",
            "cook.addedToShoppingList": "Додано до списку покупок!",
            "cook.nextStep": "Далі",
            "cook.prevStep": "Назад",
            "cook.done": "Готово",
            "cook.cookingComplete": "Приготовлено! 🎉",
            "cook.ingredientsDeducted": "Інгредієнти списані зі складу",
            "cook.confirmAndDeduct": "Підтвердити та списати",
            "cook.skipDeduction": "Пропустити",
            "cook.quitCooking": "Припинити готування?",
            "cook.quit": "Вийти",
            "cook.continueCooking": "Продовжити",
            "general.cancel": "Скасувати",
            "inventory.addNew": "Додати на склад",
            "inventory.addBatch": "Додати ще партію",
            "inventory.edit": "Редагувати продукт",
            "inventory.searchCatalog": "Пошук у каталозі",
            "inventory.newBatch": "Нова партія",
            "inventory.editCurrent": "Змінити поточний запис",
            "inventory.details": "Дані про продукт",
            "inventory.save": "Зберегти",
            "inventory.invalidQuantity": "Введіть коректну кількість",
            "inventory.noMatch": "Не знайдено в каталозі",
            "inventory.notInCatalog": "«%@» не знайдено в каталозі",
            "inventory.addToShoppingManual": "Додати «%@» до списку покупок",
            "inventory.browseCatalog": "Відкрити каталог",
            "inventory.searchPlaceholder": "Пошук продукту…",
            "inventory.existingTitle": "Продукт вже на складі",
            "inventory.existingMessage": "%@ вже є у вашому запасі",
            "shopping.toBuy": "Купити",
            "shopping.bought": "Куплено",
            "shopping.clearBought": "Очистити куплені",
            "shopping.empty": "Список покупок порожній",
            "shopping.emptyHint": "Натисніть + на відсутніх продуктах у вкладці Готувати",
            "recipes.replace": "Замінити",
            "recipes.empty": "Вільно",
            "recipes.plan": "План",
            "recipes.servings": "порц",
        ],
    ]
}
