//
//  LocalizationService.swift
//  ChefOS
//

import Foundation
import Combine
import SwiftUI

// MARK: - In-App Localization

final class LocalizationService: ObservableObject {
    @Published var language: String {
        didSet {
            UserDefaults.standard.set(language, forKey: "app_language")
        }
    }

    static let shared = LocalizationService()

    init() {
        self.language = UserDefaults.standard.string(forKey: "app_language") ?? "en"
    }

    func t(_ key: String) -> String {
        translations[language]?[key] ?? translations["en"]?[key] ?? key
    }

    // MARK: - Translations

    private let translations: [String: [String: String]] = [
        // ──────────────── English ────────────────
        "en": [
            // Tabs
            "tab.chat": "Chat",
            "tab.recipes": "Recipes",
            "tab.plan": "Plan",
            "tab.profile": "Profile",

            // Profile sections
            "profile.title": "Profile",
            "profile.personalInfo": "Personal Info",
            "profile.goals": "Goals",
            "profile.preferences": "Preferences",
            "profile.restrictions": "Restrictions",
            "profile.lifestyle": "Lifestyle",
            "profile.region": "Region",

            // Profile fields
            "profile.age": "Age",
            "profile.weight": "Weight (kg)",
            "profile.goal": "Goal",
            "profile.targetWeight": "Target weight (kg)",
            "profile.caloriesDay": "Calories / day",
            "profile.protein": "Protein (g)",
            "profile.diet": "Diet",
            "profile.cuisine": "Cuisine",
            "profile.likes": "Likes",
            "profile.dislikes": "Dislikes",
            "profile.allergies": "Allergies",
            "profile.conditions": "Conditions",
            "profile.cookingLevel": "Cooking level",
            "profile.cookingTime": "Cooking time",
            "profile.mealsDay": "Meals / day",
            "profile.country": "Country",
            "profile.currency": "Currency",
            "profile.language": "Language",
            "profile.security": "Security",
            "profile.signOut": "Sign out",
            "profile.autoSaved": "Auto-saved",

            // AI Summary
            "profile.aiTitle": "ChefOS understands you",
            "profile.aiSubtitle": "Based on your profile",

            // Tags
            "tags.addLikes": "Add likes…",
            "tags.addDislikes": "Add dislikes…",
            "tags.addAllergies": "Add allergies…",
            "tags.addConditions": "Add conditions…",

            // Fitness goals
            "goal.loseFat": "Lose fat",
            "goal.gainMuscle": "Gain muscle",
            "goal.maintainWeight": "Maintain weight",
            "goal.eatHealthier": "Eat healthier",
            "goal.medicalDiet": "Medical diet",

            // Diet types
            "diet.noRestrictions": "No restrictions",
            "diet.vegetarian": "Vegetarian",
            "diet.vegan": "Vegan",
            "diet.keto": "Keto",
            "diet.paleo": "Paleo",
            "diet.glutenFree": "Gluten-free",
            "diet.dairyFree": "Dairy-free",

            // Cuisine
            "cuisine.any": "Any",
            "cuisine.asian": "Asian",
            "cuisine.mediterranean": "Mediterranean",
            "cuisine.american": "American",
            "cuisine.mexican": "Mexican",
            "cuisine.italian": "Italian",
            "cuisine.middleEastern": "Middle Eastern",

            // Cooking level
            "cooking.beginner": "Beginner",
            "cooking.homeCook": "Home cook",
            "cooking.advanced": "Advanced",
            "cooking.chef": "Chef",

            // Cooking time
            "time.quick": "≤ 15 min",
            "time.medium": "≤ 30 min",
            "time.long": "≤ 60 min",
            "time.any": "Any",

            // AI Summary labels
            "ai.goal": "Goal",
            "ai.calories": "Calories",
            "ai.kcal": "kcal",
            "ai.protein": "Protein",
            "ai.g": "g",
            "ai.diet": "Diet",
            "ai.avoid": "Avoid",
            "ai.time": "Time",
            "ai.level": "Level",

            // Chat
            "chat.title": "Chat",
            "chat.placeholder": "Start with anything…",
            "chat.send": "Send",
            "chat.actionsLeft": "AI actions left today:",
            "chat.purchased": "purchased",
            "chat.thinking": "ChefOS is thinking",
            "chat.welcome": "Hi! I'm your ChefOS assistant.\nWhat are we cooking today?",
            "chat.error": "Sorry, I couldn't reach the server. Check your connection and try again.",
            "chat.ai": "AI",
            "chat.photo": "Photo",
            "chat.voice": "Voice",
            "chat.ingredients": "ingredients",

            // Onboarding
            "onboarding.welcome": "Welcome to ChefOS",
            "onboarding.signIn": "Sign In",
            "onboarding.signUp": "Sign Up",
            "onboarding.email": "Email",
            "onboarding.password": "Password",
            "onboarding.name": "Your name",
            "onboarding.restaurantName": "Restaurant name",
            "onboarding.passwordHint": "Min 8 characters, at least one letter and one number",
            "onboarding.noAccount": "Don't have an account?",
            "onboarding.haveAccount": "Already have an account?",
            "onboarding.continue": "Continue",
            "onboarding.done": "Done",
            "onboarding.subtitle": "Your AI cooking assistant",
            "onboarding.detecting": "Detecting your region…",
            "onboarding.currency": "Currency:",
            "onboarding.changeCountry": "Change country",
            "onboarding.createAccount": "Create Account",
            "onboarding.welcomeBack": "Welcome back to ChefOS",
            "onboarding.startJourney": "Start your cooking journey",
            "onboarding.kitchenName": "Your kitchen name",
            "onboarding.enableBiometric": "Enable",
            "onboarding.secureAccess": "Secure access to your data with",
            "onboarding.maybeLater": "Maybe later",
            "onboarding.tapToUnlock": "Tap to unlock",
            "onboarding.searchCountries": "Search countries",
            "onboarding.country": "Country",

            // Plan
            "plan.title": "Meal Plan",
            "plan.day": "Day",
            "plan.week": "Week",
            "plan.generationsLeft": "Plan generations left",
            "plan.resetsIn": "Resets in",
            "plan.saves": "This plan saves you",
            "plan.today": "today",
            "plan.overBudget": "You're over budget — Optimize now",
            "plan.smartPlan": "Smart Plan",
            "plan.generating": "Generating…",
            "plan.aiThinking": "AI is thinking",
            "plan.generateAll": "Generate all meals",
            "plan.optimize": "Optimize",
            "plan.planReady": "Plan ready",
            "plan.optimizedGoals": "— optimized for your goals",
            "plan.addedTo": "Added to",
            "plan.weekOverview": "Week Overview",
            "plan.meals": "meals",
            "plan.days": "days",
            "plan.noMeals": "No meals planned",
            "plan.tapGenerate": "Tap to generate",
            "plan.mainMeal": "Main meal",
            "plan.replace": "Replace",
            "plan.addMeal": "Add meal",
            "plan.breakfast": "Breakfast",
            "plan.lunch": "Lunch",
            "plan.dinner": "Dinner",

            // Recipes
            "recipes.title": "Recipes",
            "recipes.search": "Search recipes…",
            "recipes.searchStock": "Search stock…",
            "recipes.stock": "Stock",
            "recipes.cook": "Cook",
            "recipes.total": "Total",
            "recipes.items": "Items",
            "recipes.expiring": "Expiring",
            "recipes.noItems": "No items found",
            "recipes.scanReceipt": "Scan a receipt in Chat to add items",
            "recipes.strategy": "Strategy for today",
            "recipes.basedOnStock": "Based on your stock",
            "recipes.canCookNow": "Can cook now",
            "recipes.canCook": "can cook now",
            "recipes.missingIngredients": "Missing ingredients",
            "recipes.missing": "missing",
            "recipes.noRecipes": "No recipes found",
            "recipes.cookBtn": "Cook",
            "recipes.cookNow": "Cook now",
            "recipes.addToPlan": "Add to plan",
            "recipes.added": "Added",
            "recipes.addShopping": "Add to shopping list",
            "recipes.addMissingShopping": "Add missing to shopping list",
            "recipes.showIngredients": "Show ingredients",
            "recipes.hideIngredients": "Hide ingredients",
            "recipes.ingredients": "Ingredients",
            "recipes.steps": "Steps",
            "recipes.portion": "/ portion",
            "recipes.totalCost": "total",
            "recipes.ofBudget": "of budget",
            "recipes.allInStock": "All ingredients in stock",
            "recipes.missingCount": "Missing %d ingredient(s)",
            "recipes.cooked": "Cooked!",
            "recipes.stockUpdated": "Stock updated",
            "recipes.expirestoday": "expires today",
            "recipes.daysLeft": "d left",
            "recipes.replace": "Replace",
            "recipes.empty": "Empty",
            "recipes.plan": "Plan",
            "recipes.servings": "srv",
        ],
        "ru": [
            "tab.chat": "Чат",
            "tab.recipes": "Рецепты",
            "tab.plan": "План",
            "tab.profile": "Профиль",

            "profile.title": "Профиль",
            "profile.personalInfo": "Личные данные",
            "profile.goals": "Цели",
            "profile.preferences": "Предпочтения",
            "profile.restrictions": "Ограничения",
            "profile.lifestyle": "Образ жизни",
            "profile.region": "Регион",

            "profile.age": "Возраст",
            "profile.weight": "Вес (кг)",
            "profile.goal": "Цель",
            "profile.targetWeight": "Целевой вес (кг)",
            "profile.caloriesDay": "Калории / день",
            "profile.protein": "Белок (г)",
            "profile.diet": "Диета",
            "profile.cuisine": "Кухня",
            "profile.likes": "Нравится",
            "profile.dislikes": "Не нравится",
            "profile.allergies": "Аллергии",
            "profile.conditions": "Заболевания",
            "profile.cookingLevel": "Уровень готовки",
            "profile.cookingTime": "Время готовки",
            "profile.mealsDay": "Приёмов пищи / день",
            "profile.country": "Страна",
            "profile.currency": "Валюта",
            "profile.language": "Язык",
            "profile.security": "Безопасность",
            "profile.signOut": "Выйти",
            "profile.autoSaved": "Сохранено",

            "profile.aiTitle": "ChefOS понимает вас",
            "profile.aiSubtitle": "На основе вашего профиля",

            "tags.addLikes": "Добавить…",
            "tags.addDislikes": "Добавить…",
            "tags.addAllergies": "Добавить аллергию…",
            "tags.addConditions": "Добавить заболевание…",

            "goal.loseFat": "Сбросить жир",
            "goal.gainMuscle": "Набрать мышцы",
            "goal.maintainWeight": "Поддерживать вес",
            "goal.eatHealthier": "Питаться правильнее",
            "goal.medicalDiet": "Лечебная диета",

            "diet.noRestrictions": "Без ограничений",
            "diet.vegetarian": "Вегетарианская",
            "diet.vegan": "Веганская",
            "diet.keto": "Кето",
            "diet.paleo": "Палео",
            "diet.glutenFree": "Без глютена",
            "diet.dairyFree": "Без молочных",

            "cuisine.any": "Любая",
            "cuisine.asian": "Азиатская",
            "cuisine.mediterranean": "Средиземноморская",
            "cuisine.american": "Американская",
            "cuisine.mexican": "Мексиканская",
            "cuisine.italian": "Итальянская",
            "cuisine.middleEastern": "Ближневосточная",

            "cooking.beginner": "Новичок",
            "cooking.homeCook": "Домашний повар",
            "cooking.advanced": "Продвинутый",
            "cooking.chef": "Шеф-повар",

            "time.quick": "≤ 15 мин",
            "time.medium": "≤ 30 мин",
            "time.long": "≤ 60 мин",
            "time.any": "Любое",

            "ai.goal": "Цель",
            "ai.calories": "Калории",
            "ai.kcal": "ккал",
            "ai.protein": "Белок",
            "ai.g": "г",
            "ai.diet": "Диета",
            "ai.avoid": "Избегать",
            "ai.time": "Время",
            "ai.level": "Уровень",

            "chat.title": "Чат",
            "chat.placeholder": "Начните с чего угодно…",
            "chat.send": "Отправить",
            "chat.actionsLeft": "ИИ-действий осталось сегодня:",
            "chat.purchased": "куплено",
            "chat.thinking": "ChefOS думает",
            "chat.welcome": "Привет! Я твой помощник ChefOS.\nЧто сегодня готовим?",
            "chat.error": "Не удалось связаться с сервером. Проверьте подключение.",
            "chat.ai": "ИИ",
            "chat.photo": "Фото",
            "chat.voice": "Голос",
            "chat.ingredients": "ингредиентов",

            "onboarding.welcome": "Добро пожаловать в ChefOS",
            "onboarding.signIn": "Войти",
            "onboarding.signUp": "Регистрация",
            "onboarding.email": "Email",
            "onboarding.password": "Пароль",
            "onboarding.name": "Ваше имя",
            "onboarding.restaurantName": "Название ресторана",
            "onboarding.passwordHint": "Мин. 8 символов, хотя бы одна буква и цифра",
            "onboarding.noAccount": "Нет аккаунта?",
            "onboarding.haveAccount": "Уже есть аккаунт?",
            "onboarding.continue": "Продолжить",
            "onboarding.done": "Готово",
            "onboarding.subtitle": "Ваш AI-помощник на кухне",
            "onboarding.detecting": "Определяем ваш регион…",
            "onboarding.currency": "Валюта:",
            "onboarding.changeCountry": "Изменить страну",
            "onboarding.createAccount": "Создать аккаунт",
            "onboarding.welcomeBack": "С возвращением в ChefOS",
            "onboarding.startJourney": "Начните кулинарное путешествие",
            "onboarding.kitchenName": "Название вашей кухни",
            "onboarding.enableBiometric": "Включить",
            "onboarding.secureAccess": "Безопасный доступ к данным через",
            "onboarding.maybeLater": "Может позже",
            "onboarding.tapToUnlock": "Нажмите для разблокировки",
            "onboarding.searchCountries": "Поиск стран",
            "onboarding.country": "Страна",

            "plan.title": "План питания",
            "plan.day": "День",
            "plan.week": "Неделя",
            "plan.generationsLeft": "Генераций плана осталось",
            "plan.resetsIn": "Сброс через",
            "plan.saves": "Этот план экономит вам",
            "plan.today": "сегодня",
            "plan.overBudget": "Превышен бюджет — Оптимизировать",
            "plan.smartPlan": "Умный план",
            "plan.generating": "Генерация…",
            "plan.aiThinking": "ИИ думает",
            "plan.generateAll": "Сгенерировать все приёмы",
            "plan.optimize": "Оптимизировать",
            "plan.planReady": "План готов",
            "plan.optimizedGoals": "— оптимизирован под ваши цели",
            "plan.addedTo": "Добавлено в",
            "plan.weekOverview": "Обзор недели",
            "plan.meals": "приёмов",
            "plan.days": "дней",
            "plan.noMeals": "Нет запланированных блюд",
            "plan.tapGenerate": "Нажмите для генерации",
            "plan.mainMeal": "Основной приём",
            "plan.replace": "Заменить",
            "plan.addMeal": "Добавить блюдо",
            "plan.breakfast": "Завтрак",
            "plan.lunch": "Обед",
            "plan.dinner": "Ужин",

            "recipes.title": "Рецепты",
            "recipes.search": "Поиск рецептов…",
            "recipes.searchStock": "Поиск запасов…",
            "recipes.stock": "Запасы",
            "recipes.cook": "Готовить",
            "recipes.total": "Всего",
            "recipes.items": "Позиций",
            "recipes.expiring": "Истекает",
            "recipes.noItems": "Ничего не найдено",
            "recipes.scanReceipt": "Отсканируйте чек в Чате",
            "recipes.strategy": "Стратегия на сегодня",
            "recipes.basedOnStock": "На основе ваших запасов",
            "recipes.canCookNow": "Можно приготовить сейчас",
            "recipes.canCook": "можно готовить",
            "recipes.missingIngredients": "Не хватает ингредиентов",
            "recipes.missing": "не хватает",
            "recipes.noRecipes": "Рецепты не найдены",
            "recipes.cookBtn": "Готовить",
            "recipes.cookNow": "Приготовить",
            "recipes.addToPlan": "В план",
            "recipes.added": "Добавлено",
            "recipes.addShopping": "В список покупок",
            "recipes.addMissingShopping": "Добавить недостающее в список",
            "recipes.showIngredients": "Показать ингредиенты",
            "recipes.hideIngredients": "Скрыть ингредиенты",
            "recipes.ingredients": "Ингредиенты",
            "recipes.steps": "Шаги",
            "recipes.portion": "/ порция",
            "recipes.totalCost": "всего",
            "recipes.ofBudget": "от бюджета",
            "recipes.allInStock": "Все ингредиенты есть",
            "recipes.missingCount": "Не хватает %d ингредиент(ов)",
            "recipes.cooked": "Приготовлено!",
            "recipes.stockUpdated": "Запасы обновлены",
            "recipes.expirestoday": "истекает сегодня",
            "recipes.daysLeft": "дн. осталось",
            "recipes.replace": "Заменить",
            "recipes.empty": "Свободно",
            "recipes.plan": "План",
            "recipes.servings": "порц",
        ],
        "pl": [
            "tab.chat": "Czat",
            "tab.recipes": "Przepisy",
            "tab.plan": "Plan",
            "tab.profile": "Profil",

            "profile.title": "Profil",
            "profile.personalInfo": "Dane osobowe",
            "profile.goals": "Cele",
            "profile.preferences": "Preferencje",
            "profile.restrictions": "Ograniczenia",
            "profile.lifestyle": "Styl życia",
            "profile.region": "Region",

            "profile.age": "Wiek",
            "profile.weight": "Waga (kg)",
            "profile.goal": "Cel",
            "profile.targetWeight": "Docelowa waga (kg)",
            "profile.caloriesDay": "Kalorie / dzień",
            "profile.protein": "Białko (g)",
            "profile.diet": "Dieta",
            "profile.cuisine": "Kuchnia",
            "profile.likes": "Lubię",
            "profile.dislikes": "Nie lubię",
            "profile.allergies": "Alergie",
            "profile.conditions": "Schorzenia",
            "profile.cookingLevel": "Poziom gotowania",
            "profile.cookingTime": "Czas gotowania",
            "profile.mealsDay": "Posiłków / dzień",
            "profile.country": "Kraj",
            "profile.currency": "Waluta",
            "profile.language": "Język",
            "profile.security": "Bezpieczeństwo",
            "profile.signOut": "Wyloguj",
            "profile.autoSaved": "Zapisano",

            "profile.aiTitle": "ChefOS rozumie Cię",
            "profile.aiSubtitle": "Na podstawie Twojego profilu",

            "tags.addLikes": "Dodaj…",
            "tags.addDislikes": "Dodaj…",
            "tags.addAllergies": "Dodaj alergię…",
            "tags.addConditions": "Dodaj schorzenie…",

            "goal.loseFat": "Schudnąć",
            "goal.gainMuscle": "Zbudować mięśnie",
            "goal.maintainWeight": "Utrzymać wagę",
            "goal.eatHealthier": "Jeść zdrowiej",
            "goal.medicalDiet": "Dieta lecznicza",

            "diet.noRestrictions": "Bez ograniczeń",
            "diet.vegetarian": "Wegetariańska",
            "diet.vegan": "Wegańska",
            "diet.keto": "Keto",
            "diet.paleo": "Paleo",
            "diet.glutenFree": "Bezglutenowa",
            "diet.dairyFree": "Bez nabiału",

            "cuisine.any": "Dowolna",
            "cuisine.asian": "Azjatycka",
            "cuisine.mediterranean": "Śródziemnomorska",
            "cuisine.american": "Amerykańska",
            "cuisine.mexican": "Meksykańska",
            "cuisine.italian": "Włoska",
            "cuisine.middleEastern": "Bliskowschodnia",

            "cooking.beginner": "Początkujący",
            "cooking.homeCook": "Domowy kucharz",
            "cooking.advanced": "Zaawansowany",
            "cooking.chef": "Szef kuchni",

            "time.quick": "≤ 15 min",
            "time.medium": "≤ 30 min",
            "time.long": "≤ 60 min",
            "time.any": "Dowolny",

            "ai.goal": "Cel",
            "ai.calories": "Kalorie",
            "ai.kcal": "kcal",
            "ai.protein": "Białko",
            "ai.g": "g",
            "ai.diet": "Dieta",
            "ai.avoid": "Unikaj",
            "ai.time": "Czas",
            "ai.level": "Poziom",

            "chat.title": "Czat",
            "chat.placeholder": "Zacznij od czegokolwiek…",
            "chat.send": "Wyślij",
            "chat.actionsLeft": "Pozostało akcji AI na dziś:",
            "chat.purchased": "kupione",
            "chat.thinking": "ChefOS myśli",
            "chat.welcome": "Cześć! Jestem Twoim asystentem ChefOS.\nCo dziś gotujemy?",
            "chat.error": "Nie udało się połączyć z serwerem. Sprawdź połączenie.",
            "chat.ai": "AI",
            "chat.photo": "Zdjęcie",
            "chat.voice": "Głos",
            "chat.ingredients": "składników",

            "onboarding.welcome": "Witaj w ChefOS",
            "onboarding.signIn": "Zaloguj się",
            "onboarding.signUp": "Zarejestruj się",
            "onboarding.email": "Email",
            "onboarding.password": "Hasło",
            "onboarding.name": "Twoje imię",
            "onboarding.restaurantName": "Nazwa restauracji",
            "onboarding.passwordHint": "Min. 8 znaków, co najmniej jedna litera i cyfra",
            "onboarding.noAccount": "Nie masz konta?",
            "onboarding.haveAccount": "Masz już konto?",
            "onboarding.continue": "Kontynuuj",
            "onboarding.done": "Gotowe",
            "onboarding.subtitle": "Twój asystent kulinarny AI",
            "onboarding.detecting": "Wykrywanie regionu…",
            "onboarding.currency": "Waluta:",
            "onboarding.changeCountry": "Zmień kraj",
            "onboarding.createAccount": "Utwórz konto",
            "onboarding.welcomeBack": "Witaj ponownie w ChefOS",
            "onboarding.startJourney": "Rozpocznij kulinarną podróż",
            "onboarding.kitchenName": "Nazwa Twojej kuchni",
            "onboarding.enableBiometric": "Włącz",
            "onboarding.secureAccess": "Bezpieczny dostęp do danych przez",
            "onboarding.maybeLater": "Może później",
            "onboarding.tapToUnlock": "Dotknij, aby odblokować",
            "onboarding.searchCountries": "Szukaj krajów",
            "onboarding.country": "Kraj",

            "plan.title": "Plan posiłków",
            "plan.day": "Dzień",
            "plan.week": "Tydzień",
            "plan.generationsLeft": "Pozostało generacji planu",
            "plan.resetsIn": "Reset za",
            "plan.saves": "Ten plan oszczędza",
            "plan.today": "dziś",
            "plan.overBudget": "Przekroczono budżet — Optymalizuj",
            "plan.smartPlan": "Smart Plan",
            "plan.generating": "Generowanie…",
            "plan.aiThinking": "AI myśli",
            "plan.generateAll": "Wygeneruj wszystkie posiłki",
            "plan.optimize": "Optymalizuj",
            "plan.planReady": "Plan gotowy",
            "plan.optimizedGoals": "— zoptymalizowany pod Twoje cele",
            "plan.addedTo": "Dodano do",
            "plan.weekOverview": "Przegląd tygodnia",
            "plan.meals": "posiłków",
            "plan.days": "dni",
            "plan.noMeals": "Brak zaplanowanych posiłków",
            "plan.tapGenerate": "Dotknij, aby wygenerować",
            "plan.mainMeal": "Główny posiłek",
            "plan.replace": "Zamień",
            "plan.addMeal": "Dodaj posiłek",
            "plan.breakfast": "Śniadanie",
            "plan.lunch": "Obiad",
            "plan.dinner": "Kolacja",

            "recipes.title": "Przepisy",
            "recipes.search": "Szukaj przepisów…",
            "recipes.searchStock": "Szukaj zapasów…",
            "recipes.stock": "Zapasy",
            "recipes.cook": "Gotuj",
            "recipes.total": "Razem",
            "recipes.items": "Pozycji",
            "recipes.expiring": "Wygasa",
            "recipes.noItems": "Nie znaleziono",
            "recipes.scanReceipt": "Zeskanuj paragon w Czacie",
            "recipes.strategy": "Strategia na dziś",
            "recipes.basedOnStock": "Na podstawie zapasów",
            "recipes.canCookNow": "Można ugotować teraz",
            "recipes.canCook": "można gotować",
            "recipes.missingIngredients": "Brakujące składniki",
            "recipes.missing": "brakuje",
            "recipes.noRecipes": "Nie znaleziono przepisów",
            "recipes.cookBtn": "Gotuj",
            "recipes.cookNow": "Ugotuj teraz",
            "recipes.addToPlan": "Dodaj do planu",
            "recipes.added": "Dodano",
            "recipes.addShopping": "Dodaj do listy zakupów",
            "recipes.addMissingShopping": "Dodaj brakujące do listy",
            "recipes.showIngredients": "Pokaż składniki",
            "recipes.hideIngredients": "Ukryj składniki",
            "recipes.ingredients": "Składniki",
            "recipes.steps": "Kroki",
            "recipes.portion": "/ porcja",
            "recipes.totalCost": "razem",
            "recipes.ofBudget": "budżetu",
            "recipes.allInStock": "Wszystkie składniki na stanie",
            "recipes.missingCount": "Brakuje %d składnik(ów)",
            "recipes.cooked": "Ugotowano!",
            "recipes.stockUpdated": "Zapasy zaktualizowane",
            "recipes.expirestoday": "wygasa dziś",
            "recipes.daysLeft": "dn. pozostało",
            "recipes.replace": "Zamień",
            "recipes.empty": "Wolne",
            "recipes.plan": "Plan",
            "recipes.servings": "porc",
        ],
        "uk": [
            "tab.chat": "Чат",
            "tab.recipes": "Рецепти",
            "tab.plan": "План",
            "tab.profile": "Профіль",

            "profile.title": "Профіль",
            "profile.personalInfo": "Особисті дані",
            "profile.goals": "Цілі",
            "profile.preferences": "Вподобання",
            "profile.restrictions": "Обмеження",
            "profile.lifestyle": "Спосіб життя",
            "profile.region": "Регіон",

            "profile.age": "Вік",
            "profile.weight": "Вага (кг)",
            "profile.goal": "Ціль",
            "profile.targetWeight": "Цільова вага (кг)",
            "profile.caloriesDay": "Калорії / день",
            "profile.protein": "Білок (г)",
            "profile.diet": "Дієта",
            "profile.cuisine": "Кухня",
            "profile.likes": "Подобається",
            "profile.dislikes": "Не подобається",
            "profile.allergies": "Алергії",
            "profile.conditions": "Захворювання",
            "profile.cookingLevel": "Рівень готування",
            "profile.cookingTime": "Час готування",
            "profile.mealsDay": "Прийомів їжі / день",
            "profile.country": "Країна",
            "profile.currency": "Валюта",
            "profile.language": "Мова",
            "profile.security": "Безпека",
            "profile.signOut": "Вийти",
            "profile.autoSaved": "Збережено",

            "profile.aiTitle": "ChefOS розуміє вас",
            "profile.aiSubtitle": "На основі вашого профілю",

            "tags.addLikes": "Додати…",
            "tags.addDislikes": "Додати…",
            "tags.addAllergies": "Додати алергію…",
            "tags.addConditions": "Додати захворювання…",

            "goal.loseFat": "Скинути жир",
            "goal.gainMuscle": "Набрати м'язи",
            "goal.maintainWeight": "Підтримувати вагу",
            "goal.eatHealthier": "Їсти здоровіше",
            "goal.medicalDiet": "Лікувальна дієта",

            "diet.noRestrictions": "Без обмежень",
            "diet.vegetarian": "Вегетаріанська",
            "diet.vegan": "Веганська",
            "diet.keto": "Кето",
            "diet.paleo": "Палео",
            "diet.glutenFree": "Без глютену",
            "diet.dairyFree": "Без молочних",

            "cuisine.any": "Будь-яка",
            "cuisine.asian": "Азіатська",
            "cuisine.mediterranean": "Середземноморська",
            "cuisine.american": "Американська",
            "cuisine.mexican": "Мексиканська",
            "cuisine.italian": "Італійська",
            "cuisine.middleEastern": "Близькосхідна",

            "cooking.beginner": "Початківець",
            "cooking.homeCook": "Домашній кухар",
            "cooking.advanced": "Просунутий",
            "cooking.chef": "Шеф-кухар",

            "time.quick": "≤ 15 хв",
            "time.medium": "≤ 30 хв",
            "time.long": "≤ 60 хв",
            "time.any": "Будь-який",

            "ai.goal": "Ціль",
            "ai.calories": "Калорії",
            "ai.kcal": "ккал",
            "ai.protein": "Білок",
            "ai.g": "г",
            "ai.diet": "Дієта",
            "ai.avoid": "Уникати",
            "ai.time": "Час",
            "ai.level": "Рівень",

            "chat.title": "Чат",
            "chat.placeholder": "Почніть з будь-чого…",
            "chat.send": "Надіслати",
            "chat.actionsLeft": "ШІ-дій залишилось сьогодні:",
            "chat.purchased": "куплено",
            "chat.thinking": "ChefOS думає",
            "chat.welcome": "Привіт! Я твій помічник ChefOS.\nЩо сьогодні готуємо?",
            "chat.error": "Не вдалося зв'язатися з сервером. Перевірте підключення.",
            "chat.ai": "ШІ",
            "chat.photo": "Фото",
            "chat.voice": "Голос",
            "chat.ingredients": "інгредієнтів",

            "onboarding.welcome": "Ласкаво просимо до ChefOS",
            "onboarding.signIn": "Увійти",
            "onboarding.signUp": "Реєстрація",
            "onboarding.email": "Email",
            "onboarding.password": "Пароль",
            "onboarding.name": "Ваше ім'я",
            "onboarding.restaurantName": "Назва ресторану",
            "onboarding.passwordHint": "Мін. 8 символів, хоча б одна літера і цифра",
            "onboarding.noAccount": "Немає акаунту?",
            "onboarding.haveAccount": "Вже є акаунт?",
            "onboarding.continue": "Продовжити",
            "onboarding.done": "Готово",
            "onboarding.subtitle": "Ваш AI-помічник на кухні",
            "onboarding.detecting": "Визначаємо ваш регіон…",
            "onboarding.currency": "Валюта:",
            "onboarding.changeCountry": "Змінити країну",
            "onboarding.createAccount": "Створити акаунт",
            "onboarding.welcomeBack": "З поверненням до ChefOS",
            "onboarding.startJourney": "Почніть кулінарну подорож",
            "onboarding.kitchenName": "Назва вашої кухні",
            "onboarding.enableBiometric": "Увімкнути",
            "onboarding.secureAccess": "Безпечний доступ до даних через",
            "onboarding.maybeLater": "Може пізніше",
            "onboarding.tapToUnlock": "Торкніться для розблокування",
            "onboarding.searchCountries": "Пошук країн",
            "onboarding.country": "Країна",

            "plan.title": "План харчування",
            "plan.day": "День",
            "plan.week": "Тиждень",
            "plan.generationsLeft": "Генерацій плану залишилось",
            "plan.resetsIn": "Скидання через",
            "plan.saves": "Цей план економить вам",
            "plan.today": "сьогодні",
            "plan.overBudget": "Перевищено бюджет — Оптимізувати",
            "plan.smartPlan": "Розумний план",
            "plan.generating": "Генерація…",
            "plan.aiThinking": "ШІ думає",
            "plan.generateAll": "Згенерувати всі прийоми",
            "plan.optimize": "Оптимізувати",
            "plan.planReady": "План готовий",
            "plan.optimizedGoals": "— оптимізовано під ваші цілі",
            "plan.addedTo": "Додано до",
            "plan.weekOverview": "Огляд тижня",
            "plan.meals": "прийомів",
            "plan.days": "днів",
            "plan.noMeals": "Немає запланованих страв",
            "plan.tapGenerate": "Натисніть для генерації",
            "plan.mainMeal": "Основний прийом",
            "plan.replace": "Замінити",
            "plan.addMeal": "Додати страву",
            "plan.breakfast": "Сніданок",
            "plan.lunch": "Обід",
            "plan.dinner": "Вечеря",

            "recipes.title": "Рецепти",
            "recipes.search": "Пошук рецептів…",
            "recipes.searchStock": "Пошук запасів…",
            "recipes.stock": "Запаси",
            "recipes.cook": "Готувати",
            "recipes.total": "Всього",
            "recipes.items": "Позицій",
            "recipes.expiring": "Закінчується",
            "recipes.noItems": "Нічого не знайдено",
            "recipes.scanReceipt": "Відскануйте чек у Чаті",
            "recipes.strategy": "Стратегія на сьогодні",
            "recipes.basedOnStock": "На основі ваших запасів",
            "recipes.canCookNow": "Можна приготувати зараз",
            "recipes.canCook": "можна готувати",
            "recipes.missingIngredients": "Не вистачає інгредієнтів",
            "recipes.missing": "не вистачає",
            "recipes.noRecipes": "Рецепти не знайдено",
            "recipes.cookBtn": "Готувати",
            "recipes.cookNow": "Приготувати",
            "recipes.addToPlan": "До плану",
            "recipes.added": "Додано",
            "recipes.addShopping": "До списку покупок",
            "recipes.addMissingShopping": "Додати те, що бракує",
            "recipes.showIngredients": "Показати інгредієнти",
            "recipes.hideIngredients": "Сховати інгредієнти",
            "recipes.ingredients": "Інгредієнти",
            "recipes.steps": "Кроки",
            "recipes.portion": "/ порція",
            "recipes.totalCost": "всього",
            "recipes.ofBudget": "від бюджету",
            "recipes.allInStock": "Усі інгредієнти є",
            "recipes.missingCount": "Не вистачає %d інгредієнт(ів)",
            "recipes.cooked": "Приготовлено!",
            "recipes.stockUpdated": "Запаси оновлено",
            "recipes.expirestoday": "закінчується сьогодні",
            "recipes.daysLeft": "дн. лишилось",
            "recipes.replace": "Замінити",
            "recipes.empty": "Вільно",
            "recipes.plan": "План",
            "recipes.servings": "порц",
        ],
    ]
}
